/**
 * Updated Radio Stations - 27.06.2025 10:45:29
 * Automatically generated from Radio Browser API
 * 200 tested and working Turkish radio stations
 */

export interface RadioStation {
  id: string;
  name: string;
  url: string;
  description: string;
  votes?: number;
  bitrate?: number;
  codec?: string;
  category?: string;
  isLive?: boolean;
  website?: string;
  favicon?: string;
  country?: string;
  language?: string;
  tags?: string;
  logo?: any;
}

export const RADIO_STATIONS: RadioStation[] = [
  {
    "id": "963b1f4b-0601-11e8-ae97-52543be04c81",
    "name": "Radyo Dejavu",
    "url": "http://radyodejavu.canliyayinda.com:8054/",
    "description": "AAC+ 64kbps",
    "votes": 5669,
    "bitrate": 64,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "http://www.radyodejavu.com/",
    "favicon": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Radio_icon.svg/32px-Radio_icon.svg.png"
  },
  {
    "id": "b3e6320b-0ffc-4d4e-a999-2467897b17e6",
    "name": "Radyo Fenomen",
    "url": "https://live.radyofenomen.com/fenomen/128/icecast.audio",
    "description": "turkey • AAC+ 56kbps",
    "votes": 5279,
    "bitrate": 56,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "turkey",
    "category": "Genel",
    "isLive": true,
    "website": "https://www.radyofenomen.com/",
    "favicon": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Radio_icon.svg/32px-Radio_icon.svg.png"
  },
  {
    "id": "0012c08a-31e7-48c6-87a9-7f64736e0a38",
    "name": "Metro FM",
    "url": "http://28953.live.streamtheworld.com/METRO_FMAAC_SC",
    "description": "AAC+ 64kbps",
    "votes": 10349,
    "bitrate": 64,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://metrofm.com.tr/",
    "favicon": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Radio_icon.svg/32px-Radio_icon.svg.png"
  },
  {
    "id": "f17523b9-2e77-46f3-8851-cdd842ca5b8f",
    "name": "Metro fm turkey",
    "url": "https://23543.live.streamtheworld.com:443/METRO_FM_SC",
    "description": "MP3 64kbps",
    "votes": 1153,
    "bitrate": 64,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://playerservices.streamtheworld.com/api/livestream-redirect/METRO_FM_SC?",
    "favicon": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Radio_icon.svg/32px-Radio_icon.svg.png"
  },
  {
    "id": "960969eb-0601-11e8-ae97-52543be04c81",
    "name": "Virgin Radio Türkiye",
    "url": "http://29073.live.streamtheworld.com:3690/VIRGIN_RADIO_SC",
    "description": "pop rock • MP3 64kbps",
    "votes": 17838,
    "bitrate": 64,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "pop rock",
    "category": "Müzik",
    "isLive": true,
    "website": "http://www.virginradioturkiye.com/",
    "favicon": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Radio_icon.svg/32px-Radio_icon.svg.png"
  },
  {
    "id": "c7dadc87-3c43-46f5-aa24-91e0fa9a7643",
    "name": "Joy Fm",
    "url": "http://27793.live.streamtheworld.com:3690/JOY_FMAAC_SC",
    "description": "international • AAC+ 64kbps",
    "votes": 1914,
    "bitrate": 64,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "international",
    "category": "Genel",
    "isLive": true,
    "website": "",
    "favicon": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Radio_icon.svg/32px-Radio_icon.svg.png"
  },
  {
    "id": "5509836d-9ca5-4584-bd61-86298fa725b4",
    "name": "Number one",
    "url": "https://n10101m.mediatriple.net/numberone",
    "description": "AAC+ 32kbps",
    "votes": 1777,
    "bitrate": 32,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://numberone.com.tr/",
    "favicon": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Radio_icon.svg/32px-Radio_icon.svg.png"
  },
  {
    "id": "159e4625-43d8-4cda-b98c-819edfad8667",
    "name": "Kral FM",
    "url": "http://22533.live.streamtheworld.com:3690/SUPER_FMAAC_SC",
    "description": "pop • AAC+ 64kbps",
    "votes": 4908,
    "bitrate": 64,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "pop",
    "category": "Müzik",
    "isLive": true,
    "website": "https://kraltv.com.tr/",
    "favicon": require("../../assets/kral.png")
  },
  {
    "id": "6f3d3422-9998-4079-8e1a-7d23cef150ea",
    "name": "Radyo Fenomen Clubbin",
    "url": "https://live.radyofenomen.com/fenomenclubbin/128/icecast.audio",
    "description": "club • clubbing • dance • AAC+ 56kbps",
    "votes": 694,
    "bitrate": 56,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "english,turkish",
    "tags": "club,clubbing,dance,edm,house,party,party hits,turkey",
    "category": "Genel",
    "isLive": true,
    "website": "https://radyofenomen.com/",
    "favicon": "https://cdn.radyofenomen.com/artwork/logo20.png"
  },
  {
    "id": "0a2c3506-a136-40f2-b008-38daf2b12fd6",
    "name": "TRT FM",
    "url": "https://trt.radyotvonline.net/trtfm",
    "description": "AAC+ 134kbps",
    "votes": 337,
    "bitrate": 134,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Kamu",
    "isLive": true,
    "website": "https://trt.radyotvonline.net/trtfm",
    "favicon": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Radio_icon.svg/32px-Radio_icon.svg.png"
  },
  {
    "id": "96201b3d-0601-11e8-ae97-52543be04c81",
    "name": "Arabesk FM",
    "url": "http://yayin.arabeskfm.biz:8042/",
    "description": "müzik • türkçe • AAC+ 80kbps",
    "votes": 24980,
    "bitrate": 80,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "müzik,türkçe",
    "category": "Müzik",
    "isLive": true,
    "website": "http://www.arabeskfm.biz/",
    "favicon": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Radio_icon.svg/32px-Radio_icon.svg.png"
  },
  {
    "id": "f3dfbec0-8ddb-457c-94cd-368631337c0f",
    "name": "DAMAR TURK FM",
    "url": "https://live.radyositesihazir.com:10997/",
    "description": "istanbul bagcılar • MP3 128kbps",
    "votes": 14411,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "french,german,turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://www.damarturkfm.com/",
    "favicon": "https://www.damarturkfm.com/favicon.ico"
  },
  {
    "id": "0a9a8a20-2b30-46a8-ac10-6ef06be16889",
    "name": "Radyo Duygusal",
    "url": "https://radyoduygusal.kesintisizyayin.com:9596/;*.nsv",
    "description": "AAC+ 64kbps",
    "votes": 24,
    "bitrate": 64,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://radyoduygusal.com/",
    "favicon": "https://radyoduygusal.com/uploads/favicon/oooooooo.jpg"
  },
  {
    "id": "bf3942e0-d1cb-11e8-a54a-52543be04c81",
    "name": "Best Fm",
    "url": "http://46.20.7.126/;stream.mp3",
    "description": "MP3 128kbps",
    "votes": 15830,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://www.bestfm.com.tr/",
    "favicon": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Radio_icon.svg/32px-Radio_icon.svg.png"
  },
  {
    "id": "8c0eaabf-29b1-4fae-86f1-e7cfa7ec4953",
    "name": "Radio 5 Turkey",
    "url": "http://radyo.yayin.com.tr:4108/stream",
    "description": "adult contemporary • hits • non-stop • AAC+ 128kbps",
    "votes": 8880,
    "bitrate": 128,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "english",
    "tags": "adult contemporary,hits,non-stop,top 100",
    "category": "Genel",
    "isLive": true,
    "website": "https://www.radio5.com.tr/",
    "favicon": "https://radio5.com.tr/wp-content/plugins/under-construction-page/themes/images/favicon.png"
  },
  {
    "id": "960c341d-0601-11e8-ae97-52543be04c81",
    "name": "NTV Radyo",
    "url": "http://46.20.3.207/listen.pls",
    "description": "haber • haberler • news • AAC+ 151kbps",
    "votes": 9123,
    "bitrate": 151,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "haber,haberler,news,türkçe",
    "category": "Haber",
    "isLive": true,
    "website": "http://www.ntvradyo.com.tr/Home",
    "favicon": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Radio_icon.svg/32px-Radio_icon.svg.png"
  },
  {
    "id": "31da019f-9f0a-11e9-a787-52543be04c81",
    "name": "ALTIN SARKILAR",
    "url": "http://37.247.98.8/stream/25/;",
    "description": "golden oldies • retro • MP3 128kbps",
    "votes": 7303,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "golden oldies,retro",
    "category": "Genel",
    "isLive": true,
    "website": "http://www.radyohome.com/#altinsarkilar",
    "favicon": ""
  },
  {
    "id": "8c01f241-6fe8-42b1-afd3-d6abf90ec78e",
    "name": "Ankara Havalari",
    "url": "http://37.247.98.8/stream/30/;",
    "description": "folk • MP3 128kbps",
    "votes": 7635,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "folk",
    "category": "Genel",
    "isLive": true,
    "website": "",
    "favicon": ""
  },
  {
    "id": "df369586-40fc-11e9-aa55-52543be04c81",
    "name": "Radyo 7",
    "url": "http://46.20.3.250/;stream",
    "description": "MP3 128kbps",
    "votes": 13513,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "http://www.radyo7.com/",
    "favicon": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Radio_icon.svg/32px-Radio_icon.svg.png"
  },
  {
    "id": "1e0dcee9-bfb6-41a4-8356-e8c4540dfcf0",
    "name": "Radyo Şiran",
    "url": "https://live.radyositesihazir.com/8078/stream",
    "description": "folk • MP3 128kbps",
    "votes": 12714,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "folk",
    "category": "Genel",
    "isLive": true,
    "website": "https://live.radyositesihazir.com/8078/stream",
    "favicon": ""
  },
  {
    "id": "09f8922f-56bb-41bd-ad35-a7e54c5520e3",
    "name": "KRAL TÜRK FM",
    "url": "https://live.radyositesihazir.com/8032/stream",
    "description": "MP3 128kbps",
    "votes": 7895,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Müzik",
    "isLive": true,
    "website": "https://live.radyositesihazir.com/8032/stream",
    "favicon": "https://www.kralturkfm.com/favicon.ico"
  },
  {
    "id": "360028f5-46ba-11ea-a860-52543be04c81",
    "name": "Türkülerle Türkiye",
    "url": "http://37.247.98.8/stream/22/;",
    "description": "türkü • MP3 128kbps",
    "votes": 13666,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "türkü",
    "category": "Müzik",
    "isLive": true,
    "website": "https://www.canliradyodinle.fm/radyo-turkulerle-turkiye-dinle.html",
    "favicon": ""
  },
  {
    "id": "1e3038cc-eafc-45d0-a2e5-ef4c5d40494a",
    "name": "Baba Radyo",
    "url": "http://46.20.7.116/",
    "description": "folk • AAC+ 64kbps",
    "votes": 6776,
    "bitrate": 64,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "folk",
    "category": "Genel",
    "isLive": true,
    "website": "",
    "favicon": ""
  },
  {
    "id": "33128b7d-e1b9-46e3-be4d-8515b186a9a2",
    "name": "90lar turkey",
    "url": "http://37.247.98.8/stream/166/",
    "description": "MP3 128kbps",
    "votes": 2710,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "http://37.247.98.8/stream/166/",
    "favicon": ""
  },
  {
    "id": "8b4be047-aeac-4ccf-8eb5-35bc2f9740df",
    "name": "Turku Radyo",
    "url": "http://radyo.turkuradyo.net:4591/turkuradyo",
    "description": "folk • MP3 64kbps",
    "votes": 3348,
    "bitrate": 64,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "folk",
    "category": "Genel",
    "isLive": true,
    "website": "",
    "favicon": ""
  },
  {
    "id": "943a244d-171c-11e8-ae97-52543be04c81",
    "name": "Radyo Vatan Türkü",
    "url": "http://95.0.173.195:9000/turku",
    "description": "MP3 128kbps",
    "votes": 5367,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Müzik",
    "isLive": true,
    "website": "",
    "favicon": ""
  },
  {
    "id": "04407d31-2cc0-11e8-91bf-52543be04c81",
    "name": "dinamo.fm sleep",
    "url": "http://channels.dinamo.fm/sleep-mp3",
    "description": "ambient • chillout • lullaby • Istanbul • MP3 320kbps",
    "votes": 5558,
    "bitrate": 320,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "ambient,chillout,lullaby,relaxing,sleep,zen",
    "category": "Genel",
    "isLive": true,
    "website": "http://www.dinamo.fm/",
    "favicon": "https://www.dinamo.fm/favicons/dinamo-sleep-favicon.jpg"
  },
  {
    "id": "a31ff324-2ae1-11e9-a35e-52543be04c81",
    "name": "Radyo Voyage",
    "url": "http://voyagewmp.radyotvonline.com/;stream.mp3",
    "description": "folk • mood • relaxing • Istanbul • MP3 224kbps",
    "votes": 3328,
    "bitrate": 224,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "folk,mood,relaxing,world",
    "category": "Genel",
    "isLive": true,
    "website": "http://radyovoyage.com/",
    "favicon": ""
  },
  {
    "id": "63410135-4ae6-11e8-9b06-52543be04c81",
    "name": "RS FM",
    "url": "https://icecast-rian.cdnvideo.ru/voicestm",
    "description": "MP3 128kbps",
    "votes": 2906,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "",
    "favicon": ""
  },
  {
    "id": "0edc51ea-fc6b-4ab8-a687-8dde4730007b",
    "name": "Pal station",
    "url": "http://shoutcast.radyogrup.com:1020/",
    "description": "AAC+ 128kbps",
    "votes": 3060,
    "bitrate": 128,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://palstation106.com/",
    "favicon": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Radio_icon.svg/32px-Radio_icon.svg.png"
  },
  {
    "id": "de28a78a-6cee-453d-b9df-13557334dfdb",
    "name": "Radyo Seymen",
    "url": "https://yayin.radyoseymen.com.tr:1070/stream",
    "description": "AAC+ 128kbps",
    "votes": 4299,
    "bitrate": 128,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://www.radyoseymen.com.tr/",
    "favicon": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Radio_icon.svg/32px-Radio_icon.svg.png"
  },
  {
    "id": "706def0c-7017-4601-8305-db1cdb2e9420",
    "name": "Kral FM",
    "url": "https://27743.live.streamtheworld.com:443/SUPER_FM_SC",
    "description": "pop • MP3 64kbps",
    "votes": 3411,
    "bitrate": 64,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "pop",
    "category": "Müzik",
    "isLive": true,
    "website": "https://kraltv.com.tr/",
    "favicon": require("../../assets/kral.png")
  },
  {
    "id": "fd92e72f-2cbe-11e8-91bf-52543be04c81",
    "name": "dinamo.fm deep",
    "url": "http://channels.dinamo.fm/deep-mp3",
    "description": "deep house • house • nu disco • Istanbul • MP3 320kbps",
    "votes": 2342,
    "bitrate": 320,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "deep house,house,nu disco",
    "category": "Genel",
    "isLive": true,
    "website": "http://www.dinamo.fm/",
    "favicon": "https://www.dinamo.fm/favicons/dinamo-deep-favicon.jpg"
  },
  {
    "id": "2815bbc7-2cbf-11e8-91bf-52543be04c81",
    "name": "dinamo.fm caffe",
    "url": "http://channels.dinamo.fm/caffe-mp3",
    "description": "chillout • lounge • relaxing • Istanbul • MP3 320kbps",
    "votes": 1356,
    "bitrate": 320,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "chillout,lounge,relaxing",
    "category": "Genel",
    "isLive": true,
    "website": "http://www.dinamo.fm/",
    "favicon": "https://www.dinamo.fm/favicons/dinamo-caffe-favicon.jpg"
  },
  {
    "id": "9626456e-0601-11e8-ae97-52543be04c81",
    "name": "Dost",
    "url": "http://yayin1.yayindakiler.com:3156/",
    "description": "AAC+ 128kbps",
    "votes": 1607,
    "bitrate": 128,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "http://dostfm.com/",
    "favicon": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Radio_icon.svg/32px-Radio_icon.svg.png"
  },
  {
    "id": "8c76958a-2cbf-11e8-91bf-52543be04c81",
    "name": "dinamo.fm discotheque",
    "url": "http://channels.dinamo.fm/discotheque-mp3",
    "description": "70s • disco • disco funk • Istanbul • MP3 320kbps",
    "votes": 1218,
    "bitrate": 320,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "70s,disco,disco funk,funk",
    "category": "Genel",
    "isLive": true,
    "website": "http://www.dinamo.fm/",
    "favicon": "https://www.dinamo.fm/favicons/dinamo-disco-favicon.jpg"
  },
  {
    "id": "4bead555-fefa-401b-b9e1-e5f525c714b8",
    "name": "Numberone Turk",
    "url": "https://n10101m.mediatriple.net/numberoneturk",
    "description": "pop • AAC+ 32kbps",
    "votes": 1468,
    "bitrate": 32,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "pop",
    "category": "Müzik",
    "isLive": true,
    "website": "https://www.numberone.com.tr/2015/12/17/nr1-turk-fm-dinle-canli-radyo-dinle/",
    "favicon": ""
  },
  {
    "id": "97f3bb39-24a0-461d-b282-b0ccae5a12c4",
    "name": "Slow Turk",
    "url": "https://radyo.duhnet.tv/ak_dtvh_slowturk",
    "description": "Türk Radyosu",
    "votes": 1475,
    "bitrate": 128,
    "codec": "AAC",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://www.slowturk.com.tr/",
    "favicon": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Radio_icon.svg/32px-Radio_icon.svg.png"
  },
  {
    "id": "2a372113-4b74-41aa-a1e8-3dcb5d66de61",
    "name": "JOY TÜRK TURKEY",
    "url": "https://27753.live.streamtheworld.com:443/JOY_TURK_SC?/",
    "description": "MP3 64kbps",
    "votes": 1830,
    "bitrate": 64,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Müzik",
    "isLive": true,
    "website": "https://joyturk.com/",
    "favicon": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Radio_icon.svg/32px-Radio_icon.svg.png"
  },
  {
    "id": "0dc6e3f7-b313-4bc4-a06a-94f05c51dff5",
    "name": "pop 90 turkey",
    "url": "http://25703.live.streamtheworld.com:3690/POP90AAC_SC",
    "description": "AAC+ 64kbps",
    "votes": 2571,
    "bitrate": 64,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Müzik",
    "isLive": true,
    "website": "http://provisioning.streamtheworld.com/pls/POP90AAC.pls",
    "favicon": ""
  },
  {
    "id": "6f54c6a5-7032-4a86-b00e-21f1169f678a",
    "name": "SUPER FM 2 TURKEY",
    "url": "https://25603.live.streamtheworld.com:443/SUPER2_SC?/",
    "description": "MP3 64kbps",
    "votes": 1231,
    "bitrate": 64,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://playerservices.streamtheworld.com/api/livestream-redirect/SUPER2_SC?/",
    "favicon": "",
    "logo": require("../../assets/super.png")
  },
  {
    "id": "775bea1d-8c92-11e9-ad01-52543be04c81",
    "name": "Gözyaşı FM",
    "url": "http://yayin1.canliyayin.org:8700/;*.mp3",
    "description": "islamic • Istanbul • MP3 64kbps",
    "votes": 1094,
    "bitrate": 64,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "islamic",
    "category": "Dini",
    "isLive": true,
    "website": "http://www.konyagozyasifm.com/",
    "favicon": ""
  },
  {
    "id": "f940cc74-1673-4bc8-adbc-832d5d51a012",
    "name": "Kurd1 FM",
    "url": "https://listen.radioking.com/radio/119251/stream/158701",
    "description": "folk music • kurdish folk music • kurdish songs • MP3 128kbps",
    "votes": 1142,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "kurdish",
    "tags": "folk music,kurdish folk music,kurdish songs",
    "category": "Müzik",
    "isLive": true,
    "website": "https://www.kurd1radyo.com/",
    "favicon": ""
  },
  {
    "id": "2871e14f-254c-4b0a-b506-c59bc6175e43",
    "name": "Park Fm",
    "url": "http://yayin.netradyom.com:8050/PARKFM/",
    "description": "folk • AAC+ 32kbps",
    "votes": 1024,
    "bitrate": 32,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "folk",
    "category": "Genel",
    "isLive": true,
    "website": "",
    "favicon": ""
  },
  {
    "id": "9aab2dd5-ec19-469a-a048-e3f7c63f8585",
    "name": "Radyo Ekin",
    "url": "http://yayin.turkhosted.com:6006/",
    "description": "classical • MP3 128kbps",
    "votes": 1005,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "classical",
    "category": "Klasik",
    "isLive": true,
    "website": "",
    "favicon": ""
  },
  {
    "id": "960e1f3e-0601-11e8-ae97-52543be04c81",
    "name": "Magic FM",
    "url": "http://yayin1.yayindakiler.com:3032/",
    "description": "MP3 128kbps",
    "votes": 954,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "",
    "favicon": ""
  },
  {
    "id": "7ccb7f82-7dd6-11e8-b68b-52543be04c81",
    "name": "Radyo ODTU",
    "url": "https://stream3.radyoodtu.com.tr:8000/;",
    "description": "AAC+ 48kbps",
    "votes": 1044,
    "bitrate": 48,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "http://www.radyoodtu.com.tr/",
    "favicon": ""
  },
  {
    "id": "585600d9-bdc4-4a2e-93c5-2421041cc55c",
    "name": "Radyo 45lik yeni",
    "url": "https://stream.radyo45lik.com:4545/",
    "description": "70s • 80s • 90s • AAC+ 128kbps",
    "votes": 1189,
    "bitrate": 128,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "70s,80s,90s,nostalgic,retro",
    "category": "Genel",
    "isLive": true,
    "website": "https://www.radyo45lik.com/",
    "favicon": ""
  },
  {
    "id": "7f29690c-2cc0-11e8-91bf-52543be04c81",
    "name": "dinamo.fm locodyno",
    "url": "http://channels.dinamo.fm/locodyno-mp3",
    "description": "dj sets • dub • electronic • Istanbul • MP3 320kbps",
    "votes": 877,
    "bitrate": 320,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "dj sets,dub,electronic,house,mix,nu disco,techno",
    "category": "Genel",
    "isLive": true,
    "website": "http://www.dinamo.fm/",
    "favicon": "https://www.dinamo.fm/favicons/dinamo-locodyno-favicon.jpg"
  },
  {
    "id": "a4c69a47-bb4f-4a09-a1c7-8c89b554fd53",
    "name": "lokum fm",
    "url": "http://37.247.98.9/stream/493/?/;stream.mp3",
    "description": "country • AAC+ 48kbps",
    "votes": 874,
    "bitrate": 48,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "country",
    "category": "Genel",
    "isLive": true,
    "website": "",
    "favicon": ""
  },
  {
    "id": "a4a06619-c8fc-43aa-b574-48b350b5e213",
    "name": "Havin FM",
    "url": "http://yayin6.radyohizmeti.com:7050/;stream.mp3",
    "description": "folk music • kurdish folk music • kurdish songs • MP3 64kbps",
    "votes": 813,
    "bitrate": 64,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "kurdish",
    "tags": "folk music,kurdish folk music,kurdish songs",
    "category": "Müzik",
    "isLive": true,
    "website": "http://havinfm.com/",
    "favicon": ""
  },
  {
    "id": "7ab25d55-40ef-4dcc-8e85-1dd99650d830",
    "name": "Halk Radyo",
    "url": "https://anadolu.liderhost.com.tr:10876/;",
    "description": "classical • AAC+ 104kbps",
    "votes": 841,
    "bitrate": 104,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "classical",
    "category": "Klasik",
    "isLive": true,
    "website": "",
    "favicon": ""
  },
  {
    "id": "962886df-0601-11e8-ae97-52543be04c81",
    "name": "Radyo ILEF Ankara",
    "url": "http://radyo.cc.ankara.edu.tr:8089/;",
    "description": "ankara • ankara üniversitesi • college radio • AAC+ 52kbps",
    "votes": 762,
    "bitrate": 52,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "ankara,ankara üniversitesi,college radio,easy listening,i̇letişim fakültesi,jazz",
    "category": "Genel",
    "isLive": true,
    "website": "http://ilef.ankara.edu.tr/radyoilef/",
    "favicon": ""
  },
  {
    "id": "faa8e98f-cb42-4e46-9148-71d2ca6e7537",
    "name": "Erzincan Cem Radyo",
    "url": "https://erzincan.80.yayin.com.tr/stream",
    "description": "classical • AAC+ 96kbps",
    "votes": 724,
    "bitrate": 96,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "classical",
    "category": "Klasik",
    "isLive": true,
    "website": "",
    "favicon": ""
  },
  {
    "id": "1210df35-9d44-4f35-b70e-f3c81428cd27",
    "name": "Avrasya Türk Radyo",
    "url": "https://sslyayin.netyayin.net:10909/",
    "description": "classical • AAC+ 96kbps",
    "votes": 706,
    "bitrate": 96,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "classical",
    "category": "Müzik",
    "isLive": true,
    "website": "https://sslyayin.netyayin.net:10909/",
    "favicon": ""
  },
  {
    "id": "df6f9f99-dd61-4570-812c-398a06c3da4d",
    "name": "KEYF STATION",
    "url": "http://yayin.radyomadyo.com:8002/stream",
    "description": "pop • AAC+ 128kbps",
    "votes": 724,
    "bitrate": 128,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "pop",
    "category": "Müzik",
    "isLive": true,
    "website": "",
    "favicon": ""
  },
  {
    "id": "961f44d7-0601-11e8-ae97-52543be04c81",
    "name": "Radyo A (Radyo Anadolu Üniversitesi)",
    "url": "http://canli.radyoa.anadolu.edu.tr:44445/Radyo_A_MP3",
    "description": "blues • folk • pop rock • Eskişehir • MP3 128kbps",
    "votes": 760,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "blues,folk,pop rock,university radio",
    "category": "Müzik",
    "isLive": true,
    "website": "http://www.radyoa.anadolu.edu.tr/",
    "favicon": ""
  },
  {
    "id": "ccfd28c8-9f0a-11e9-a787-52543be04c81",
    "name": "Borusan Klasik",
    "url": "http://27783.live.streamtheworld.com/BORUSAN_KLASIKAAC_SC",
    "description": "classical • AAC+ 64kbps",
    "votes": 699,
    "bitrate": 64,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "classical",
    "category": "Klasik",
    "isLive": true,
    "website": "https://karnaval.com/radyolar/borusanklasik",
    "favicon": ""
  },
  {
    "id": "3951ff60-8bd1-11e9-ad01-52543be04c81",
    "name": "Radio Antalya",
    "url": "https://my.radiolize.com/radio/8000/radio.mp3",
    "description": "downtempo • electronica • indie • Antalya • AAC 320kbps",
    "votes": 655,
    "bitrate": 320,
    "codec": "AAC",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "downtempo,electronica,indie,public radio",
    "category": "Genel",
    "isLive": true,
    "website": "https://radioantalya.com/",
    "favicon": "https://radioantalya.com/favicon.ico"
  },
  {
    "id": "4533a6a3-0b8e-476b-b0ec-b4a56162caa6",
    "name": "Pir Yolu",
    "url": "http://radyopiryolu.canliyayinda.com:8165/",
    "description": "classical • MP3 128kbps",
    "votes": 628,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "classical",
    "category": "Klasik",
    "isLive": true,
    "website": "http://radyopiryolu.canliyayinda.com:8165/",
    "favicon": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Radio_icon.svg/32px-Radio_icon.svg.png"
  },
  {
    "id": "0da692ab-2ee2-45e6-8303-26ff30949f91",
    "name": "Pal Doğa",
    "url": "http://shoutcast.radyogrup.com:1040/;*.mp3",
    "description": "classical • AAC+ 32kbps",
    "votes": 674,
    "bitrate": 32,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "classical",
    "category": "Klasik",
    "isLive": true,
    "website": "",
    "favicon": ""
  },
  {
    "id": "1e9396bb-8c93-11e9-ad01-52543be04c81",
    "name": "Radyo Kur'an",
    "url": "http://yayin.liderhost.net:8555/;*.mp3",
    "description": "islamic • Istanbul • AAC+ 72kbps",
    "votes": 651,
    "bitrate": 72,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "islamic",
    "category": "Dini",
    "isLive": true,
    "website": "http://www.radyokuran.net/",
    "favicon": ""
  },
  {
    "id": "b0d6423b-dd92-4267-9b91-f3d291cf8849",
    "name": "BAYRAM FM TURKEY",
    "url": "https://sslyayin.netyayin.net/3442/stream",
    "description": "AAC+ 96kbps",
    "votes": 587,
    "bitrate": 96,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://sslyayin.netyayin.net/3442/stream",
    "favicon": ""
  },
  {
    "id": "14db05f4-b028-40dc-a13f-c53d068d929e",
    "name": "Habertürk Radyo",
    "url": "https://haberturkradyo.radyotvonline.net/haberturkradyo",
    "description": "AAC 128kbps",
    "votes": 699,
    "bitrate": 128,
    "codec": "AAC",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Haber",
    "isLive": true,
    "website": "https://www.haberturkradyo.com.tr/",
    "favicon": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Radio_icon.svg/32px-Radio_icon.svg.png"
  },
  {
    "id": "306970f9-8063-481d-9f6b-00b99833d206",
    "name": "Radyo Banko",
    "url": "http://yayin.netradyom.com:9910/RADYOBANKO",
    "description": "folk • AAC+ 32kbps",
    "votes": 524,
    "bitrate": 32,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "folk",
    "category": "Genel",
    "isLive": true,
    "website": "http://radyobanko.com/",
    "favicon": ""
  },
  {
    "id": "2c1b76ea-4675-4e64-a282-50bdd4a9a238",
    "name": "Can Radyo",
    "url": "http://yayin1.yayindakiler.com:3124/;",
    "description": "classical • AAC+ 128kbps",
    "votes": 544,
    "bitrate": 128,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "classical",
    "category": "Klasik",
    "isLive": true,
    "website": "",
    "favicon": ""
  },
  {
    "id": "43b61654-8c90-11e9-ad01-52543be04c81",
    "name": "Ribat FM",
    "url": "http://yayin1.canliyayin.org:7010/;*.mp3",
    "description": "islamic • Konya • MP3 64kbps",
    "votes": 535,
    "bitrate": 64,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "islamic",
    "category": "Dini",
    "isLive": true,
    "website": "http://www.ribatfm.com.tr/",
    "favicon": ""
  },
  {
    "id": "57d6c252-a148-4e96-9602-39f3d6f22eb1",
    "name": "Radio 44",
    "url": "https://radyo44.80.yayin.com.tr/stream",
    "description": "hits • pop • top40 • MP3 128kbps",
    "votes": 580,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "hits,pop,top40,turkish music",
    "category": "Müzik",
    "isLive": true,
    "website": "https://radyo44.com.tr/",
    "favicon": "https://radyo44.com.tr/favicons/favicon-32x32.png"
  },
  {
    "id": "ce11fd33-2cbf-11e8-91bf-52543be04c81",
    "name": "dinamo.fm smog",
    "url": "http://channels.dinamo.fm/smog-mp3",
    "description": "deep • dub • electronica • Istanbul • MP3 320kbps",
    "votes": 527,
    "bitrate": 320,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "deep,dub,electronica,idm",
    "category": "Genel",
    "isLive": true,
    "website": "http://www.dinamo.fm/",
    "favicon": "https://www.dinamo.fm/favicons/dinamo-smog-favicon.jpg"
  },
  {
    "id": "960e363d-0601-11e8-ae97-52543be04c81",
    "name": "Max Fm 95.8 Maximum Music",
    "url": "http://live2.radyotvonline.com:8025/",
    "description": "AAC+ 64kbps",
    "votes": 564,
    "bitrate": 64,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "english",
    "tags": "",
    "category": "Müzik",
    "isLive": true,
    "website": "http://www.maxfm.com.tr/",
    "favicon": ""
  },
  {
    "id": "4d13d500-fb68-4d6f-ab81-fa0ce325702a",
    "name": "HAYATMİX ",
    "url": "https://hayatmix.yayin.com.tr/mp3",
    "description": "classical • MP3 192kbps",
    "votes": 530,
    "bitrate": 192,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "classical",
    "category": "Klasik",
    "isLive": true,
    "website": "",
    "favicon": ""
  },
  {
    "id": "e07ce960-0fca-49c5-9f9f-4aa24feb77a8",
    "name": "Gundi FM",
    "url": "http://gundifm.ozelip.com:7830/;",
    "description": "folk music • kurdish folk music • kurdish songs • MP3 64kbps",
    "votes": 559,
    "bitrate": 64,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "kurdish",
    "tags": "folk music,kurdish folk music,kurdish songs",
    "category": "Müzik",
    "isLive": true,
    "website": "http://www.gundifm.com/",
    "favicon": "https://yt3.ggpht.com/ytc/AKedOLSnbp3j7UCOUCra41mcQXEaeuobWPad1G7bwOsZDw=s900-c-k-c0x00ffffff-no-rj"
  },
  {
    "id": "cad85f62-a486-4b1c-b90d-9a3a5956330b",
    "name": "KİSS LOVE RADYO TURKEY",
    "url": "https://anadolu.liderhost.com.tr:10964/",
    "description": "AAC+ 128kbps",
    "votes": 506,
    "bitrate": 128,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://anadolu.liderhost.com.tr:10964/",
    "favicon": ""
  },
  {
    "id": "45bb5fc8-84df-4561-b282-935bb5dd7c86",
    "name": "dinamo.fm fluent",
    "url": "http://channels.dinamo.fm/fluent-mp3",
    "description": "atmospheric • d&b • drum and bass • MP3 320kbps",
    "votes": 464,
    "bitrate": 320,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "atmospheric,d&b,drum and bass,liquid",
    "category": "Genel",
    "isLive": true,
    "website": "http://www.dinamo.fm/",
    "favicon": "https://www.dinamo.fm/favicons/dinamo-fluent-favicon.jpg"
  },
  {
    "id": "2b6a1628-dce1-48c4-bafc-9e2a37c25bd4",
    "name": "Pazarcık",
    "url": "http://yayin.pazarcikfm.com:9090/",
    "description": "classical • MP3 128kbps",
    "votes": 449,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "classical",
    "category": "Klasik",
    "isLive": true,
    "website": "",
    "favicon": ""
  },
  {
    "id": "dfd64544-4dd7-49a9-8fd2-90a571b418ec",
    "name": "Radio Ava Turkiye",
    "url": "http://play.markaradyo.com:8002/stream",
    "description": "pop music • MP3 128kbps",
    "votes": 403,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "persian,turkish",
    "tags": "pop music",
    "category": "Müzik",
    "isLive": true,
    "website": "http://play.markaradyo.com/",
    "favicon": ""
  },
  {
    "id": "088c2b87-4c3d-4fb0-ba51-f80690de89b0",
    "name": "Azadi Fm",
    "url": "https://amed.ozelip.com/8040/;",
    "description": "MP3 64kbps",
    "votes": 486,
    "bitrate": 64,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "kurdish,turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "http://canlikurtceradyodinle.com/havin-fm-canli-yayin/",
    "favicon": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Radio_icon.svg/32px-Radio_icon.svg.png"
  },
  {
    "id": "354ffe25-8a45-4534-888b-c900054c1ba7",
    "name": "JOY TÜRK ROCK TURKEY",
    "url": "https://27873.live.streamtheworld.com:443/JOYTURK_ROCK_SC?/",
    "description": "MP3 64kbps",
    "votes": 471,
    "bitrate": 64,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Müzik",
    "isLive": true,
    "website": "https://playerservices.streamtheworld.com/api/livestream-redirect/JOYTURK_ROCK_SC?/",
    "favicon": ""
  },
  {
    "id": "0b70b296-3335-4d7d-bb55-a60d2c4071b1",
    "name": "BİLECİK FM TURKEY",
    "url": "http://bilecikfm.kesintisizyayin.com:9980/",
    "description": "AAC+ 52kbps",
    "votes": 382,
    "bitrate": 52,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "http://bilecikfm.kesintisizyayin.com:9980/",
    "favicon": ""
  },
  {
    "id": "960e2cdc-0601-11e8-ae97-52543be04c81",
    "name": "Radyo Hayat",
    "url": "http://live4.radyotvonline.com:9450/",
    "description": "AAC+ 128kbps",
    "votes": 378,
    "bitrate": 128,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "",
    "favicon": ""
  },
  {
    "id": "961fbfc8-0601-11e8-ae97-52543be04c81",
    "name": "Radyo Eksen 96.2",
    "url": "http://eksenwmp.radyotvonline.com/;stream.mp3",
    "description": "alternative rock • indie • istanbul • Istanbul • MP3 224kbps",
    "votes": 333,
    "bitrate": 224,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "alternative rock,indie,istanbul,rock",
    "category": "Müzik",
    "isLive": true,
    "website": "http://www.radioeksen.com/",
    "favicon": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Radio_icon.svg/32px-Radio_icon.svg.png"
  },
  {
    "id": "c1e2e152-71d0-458f-9c41-5fb54a33dbf8",
    "name": "TRT Radyo 1",
    "url": "https://trt.radyotvonline.net/trt1",
    "description": "AAC+ 136kbps",
    "votes": 351,
    "bitrate": 136,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Kamu",
    "isLive": true,
    "website": "https://radyo.trt.net.tr/kanallar/radyo-1",
    "favicon": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Radio_icon.svg/32px-Radio_icon.svg.png"
  },
  {
    "id": "24a3740f-4a8e-46e5-8b39-c8b4a2730ded",
    "name": "retro turk",
    "url": "http://25633.live.streamtheworld.com:3690/RETROTURKAAC_SC",
    "description": "AAC+ 64kbps",
    "votes": 379,
    "bitrate": 64,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://www.karnaval.com/",
    "favicon": ""
  },
  {
    "id": "a404045e-bd13-4e15-a591-6c81b846b1b8",
    "name": "Med Radyo",
    "url": "http://medradyo.kesintisizyayin.com:8062/stream",
    "description": "classical • MP3 64kbps",
    "votes": 305,
    "bitrate": 64,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "classical",
    "category": "Klasik",
    "isLive": true,
    "website": "",
    "favicon": ""
  },
  {
    "id": "474b5f9f-6202-4928-a3c0-0a9068ce040e",
    "name": "102.1 Arabeskin Merkezi Fm",
    "url": "http://canli.arabeskinmerkezi.com:9180/stream",
    "description": "arabesk • arabesk fantazi • arabic • Istanbul • MP3 128kbps",
    "votes": 298,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "azerbaijani,turkish,turkmen",
    "tags": "arabesk,arabesk fantazi,arabic,pop",
    "category": "Müzik",
    "isLive": true,
    "website": "https://www.arabeskinmerkezi.com/",
    "favicon": "https://images.keepone.net/1376-2022-10-17.png"
  },
  {
    "id": "c7a30d78-9abb-42e9-9b89-72dba884f2f3",
    "name": "Denge Gundeme",
    "url": "http://kesintisizyayin.com:1656/",
    "description": "classical • MP3 128kbps",
    "votes": 272,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "classical",
    "category": "Klasik",
    "isLive": true,
    "website": "",
    "favicon": ""
  },
  {
    "id": "a98e0969-7f9d-44ca-9c46-75b86444d6d4",
    "name": "KUZEY FM TURKEY",
    "url": "http://yayin.yayindakiler.com:3028/",
    "description": "AAC+ 112kbps",
    "votes": 264,
    "bitrate": 112,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "http://yayin.yayindakiler.com:3028/",
    "favicon": ""
  },
  {
    "id": "b1443978-7de0-11e8-b68b-52543be04c81",
    "name": "MaxFM",
    "url": "http://live.radyotvonline.com:8090/;",
    "description": "MP3 128kbps",
    "votes": 283,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "",
    "favicon": ""
  },
  {
    "id": "f34bebba-3a9e-4636-a593-d29538d7ed76",
    "name": "radyo mezopotamya",
    "url": "https://anadolu.liderhost.com.tr/9404/stream",
    "description": "MP3 128kbps",
    "votes": 289,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "arabic,kurdish,turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://www.artuklumezopotamyaradyo.com/",
    "favicon": ""
  },
  {
    "id": "86f7abc5-a65e-43ac-817f-e3b87f734fa1",
    "name": "Tezene",
    "url": "http://37.247.98.8/stream/22/.mp3?%26token=Bsx3vK2u28-xMp98IZDV2Q%26expires=1618686860%27%20type=%27audio/mp3%27&rd2=%27https://radyo.vip/stream",
    "description": "classical • MP3 128kbps",
    "votes": 267,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "classical",
    "category": "Klasik",
    "isLive": true,
    "website": "",
    "favicon": ""
  },
  {
    "id": "d6a8ae1d-75fc-490f-a9fe-4fcaacaf9ba6",
    "name": "LALEGÜL FM",
    "url": "https://icecast.netmedya.net/lalegulfm",
    "description": "Türk Radyosu",
    "votes": 292,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://icecast.netmedya.net/lalegulfm",
    "favicon": ""
  },
  {
    "id": "aec438e2-74b3-11ea-b1cf-52543be04c81",
    "name": "Radyo ODTU - Rock",
    "url": "https://stream3.radyoodtu.com.tr:8000/rock",
    "description": "classic rock • hard rock • heavy metal • MP3 128kbps",
    "votes": 253,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "classic rock,hard rock,heavy metal,rock",
    "category": "Müzik",
    "isLive": true,
    "website": "https://www.radyoodtu.com.tr/",
    "favicon": ""
  },
  {
    "id": "8456989c-06fb-445c-b4d9-9a4e84d608be",
    "name": "MERKEZ FM SAMSUN TURKEY",
    "url": "http://uydu.radyotvyayini.com:8016/",
    "description": "AAC+ 160kbps",
    "votes": 259,
    "bitrate": 160,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "http://uydu.radyotvyayini.com:8016/",
    "favicon": ""
  },
  {
    "id": "15e3febd-6f60-41a9-be87-dada694c1858",
    "name": "GÖKKUŞAĞI RADYO TURKEY",
    "url": "http://gokkusagiradyo.kesintisizyayin.com:8008/",
    "description": "AAC+ 64kbps",
    "votes": 244,
    "bitrate": 64,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "http://gokkusagiradyo.kesintisizyayin.com:8008/",
    "favicon": ""
  },
  {
    "id": "b5981132-7fdd-43cf-9433-eaa712b8ee21",
    "name": "Radyo Taksi",
    "url": "https://live.radyo.in/8006/stream",
    "description": "pop • MP3 128kbps",
    "votes": 231,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "pop",
    "category": "Müzik",
    "isLive": true,
    "website": "https://radyo.taksi.com/",
    "favicon": ""
  },
  {
    "id": "e3f87568-21a6-4066-801c-7579dd93c39a",
    "name": "NUMBERONE CLASSIC TURKEY",
    "url": "https://n10101m.mediatriple.net/classic",
    "description": "AAC+ 32kbps",
    "votes": 242,
    "bitrate": 32,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://www.numberone.com.tr/",
    "favicon": ""
  },
  {
    "id": "6e02d200-31be-42ad-bbf1-1918f905f6d5",
    "name": "Onur Radyo",
    "url": "http://anadolu.liderhost.com.tr:8094/",
    "description": "classical • MP3 128kbps",
    "votes": 207,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "classical",
    "category": "Klasik",
    "isLive": true,
    "website": "",
    "favicon": ""
  },
  {
    "id": "70d5625c-8c8e-11e9-ad01-52543be04c81",
    "name": "Radyo Gül",
    "url": "http://yayin2.canliyayin.org:8866/;*.mp3",
    "description": "Istanbul • MP3 192kbps",
    "votes": 220,
    "bitrate": 192,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "http://www.radyogul.com.tr/",
    "favicon": ""
  },
  {
    "id": "81510d4f-cd42-433e-b1ef-77d2b309fa5a",
    "name": "Hemdem Radyo",
    "url": "https://radyoserver3.okeylisans.com:8040/stream",
    "description": "arabesk fantazi • turkish pop • türk halk müziği • AAC+ 96kbps",
    "votes": 206,
    "bitrate": 96,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "arabesk fantazi,turkish pop,türk halk müziği,türk pop,türk sanat,türkçe,türkü",
    "category": "Müzik",
    "isLive": true,
    "website": "https://hemdemradyo.com/",
    "favicon": "https://hemdemradyo.com/favicon.ico"
  },
  {
    "id": "429d64ec-d941-4b51-ac44-5f20e95f2f79",
    "name": "KLAS RADİO TURKEY",
    "url": "https://anadolu.liderhost.com.tr:10929/",
    "description": "AAC+ 128kbps",
    "votes": 216,
    "bitrate": 128,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://anadolu.liderhost.com.tr:10929/",
    "favicon": ""
  },
  {
    "id": "b6fbb6ea-0b7b-467a-9270-5d1e6b19d944",
    "name": "Istanbul FM",
    "url": "https://yayin.istanbulfm.com.tr/istanbulfm",
    "description": "Turkey • AAC 128kbps",
    "votes": 231,
    "bitrate": 128,
    "codec": "AAC",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://www.istanbulfm.com.tr/",
    "favicon": ""
  },
  {
    "id": "a23881c5-8c90-11e9-ad01-52543be04c81",
    "name": "Enderun FM",
    "url": "http://yayin2.canliyayin.org:7052/;*.mp3",
    "description": "islamic • Istanbul • MP3 192kbps",
    "votes": 156,
    "bitrate": 192,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "islamic",
    "category": "Dini",
    "isLive": true,
    "website": "https://enderunfm.com/",
    "favicon": "https://enderunfm.com/wp-content/uploads/2023/07/cropped-enderun_fm-180x180.png"
  },
  {
    "id": "2724a1ac-9f70-40b7-bba9-f75325e56faf",
    "name": "Radyo Yalova ",
    "url": "https://studio25.radiolize.com/radio/8200/radio.mp3",
    "description": "folk • AAC 48kbps",
    "votes": 161,
    "bitrate": 48,
    "codec": "AAC",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "folk",
    "category": "Genel",
    "isLive": true,
    "website": "https://radyoyalova.com/",
    "favicon": ""
  },
  {
    "id": "963e5f78-0601-11e8-ae97-52543be04c81",
    "name": "BRTK",
    "url": "http://sc.brtk.net:8000/",
    "description": "MP3 128kbps",
    "votes": 174,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "http://www.brtk.net/",
    "favicon": "https://brtk.net/wp-content/uploads/2024/11/28/cropped-brt-icon-180x180.png?ver=ebc4c4ff24f512d1ba2ae8331bfa527d"
  },
  {
    "id": "d3bd3543-c2af-444f-9c73-b8d3bba6e740",
    "name": "HOS MİX",
    "url": "https://anadolu.liderhost.com.tr:10871/",
    "description": "MP3 128kbps",
    "votes": 178,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://anadolu.liderhost.com.tr:10871/",
    "favicon": ""
  },
  {
    "id": "9950412a-7c6f-4107-a284-3411877f5c7c",
    "name": "Radyo Arkadaş",
    "url": "https://ssl120.radyotelekom.com.tr/9998/stream",
    "description": "classical • MP3 64kbps",
    "votes": 172,
    "bitrate": 64,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "classical",
    "category": "Klasik",
    "isLive": true,
    "website": "",
    "favicon": ""
  },
  {
    "id": "2484f562-2a83-4c6d-9f91-038644ceb11e",
    "name": "Radyo Trio",
    "url": "https://radyotrio.radyotvonline.net/radyotrio",
    "description": "MP3 128kbps",
    "votes": 193,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "türkisch",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://radyotrio.com/",
    "favicon": "null"
  },
  {
    "id": "3dee3cbf-4fbe-4be8-a78a-9ff46f776385",
    "name": "NUMBERONE JAZZ TURKEY",
    "url": "https://n10101m.mediatriple.net/jazz",
    "description": "AAC+ 32kbps",
    "votes": 172,
    "bitrate": 32,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://n10101m.mediatriple.net/jazz",
    "favicon": ""
  },
  {
    "id": "cddbc845-cd60-40ee-8962-fdefef7c7b48",
    "name": "Radyo Munzur 97.7",
    "url": "http://yayin1.yayindakiler.com:3002/;stream.nsv",
    "description": "dersim • AAC+ 128kbps",
    "votes": 153,
    "bitrate": 128,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "kirmanci,turkish",
    "tags": "dersim",
    "category": "Genel",
    "isLive": true,
    "website": "http://canlifm.com/m/ozgun/radyomunzur",
    "favicon": ""
  },
  {
    "id": "bef9a5a3-997a-42ed-a480-f0302253b7d5",
    "name": "HaYaTMiX Slow",
    "url": "https://radyo.yayin.com.tr:4090/mp3",
    "description": "MP3 128kbps",
    "votes": 148,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://www.hayatmix.com/slow/",
    "favicon": ""
  },
  {
    "id": "960e1ce4-0601-11e8-ae97-52543be04c81",
    "name": "Radyo Erkan",
    "url": "http://sunucu2.radyolarburada.com:8095/",
    "description": "AAC+ 64kbps",
    "votes": 150,
    "bitrate": 64,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "http://radyoerkan.com.tr/",
    "favicon": ""
  },
  {
    "id": "18e8abfe-b59c-40b4-b4b1-495d8fa3d61f",
    "name": "Türkrap FM",
    "url": "http://95.173.188.166:9984/stream",
    "description": "hip-hop • rap • MP3 128kbps",
    "votes": 143,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "hip-hop,rap",
    "category": "Müzik",
    "isLive": true,
    "website": "https://www.turkrapfm.net/",
    "favicon": "https://www.turkrapfm.net/favicon.ico"
  },
  {
    "id": "3acd808a-e801-43bb-bdb3-16a8f4761f0d",
    "name": "meteorolojinin sesi",
    "url": "http://radyomgm.canliyayinda.com/;stream.mp3",
    "description": "news • MP3 128kbps",
    "votes": 144,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "news",
    "category": "Haber",
    "isLive": true,
    "website": "http://radyo.mgm.gov.tr/",
    "favicon": ""
  },
  {
    "id": "87f52657-066b-4ffe-b8c5-4cc1f9476b7e",
    "name": "Dost FM",
    "url": "http://yayin.dostfm.com:8920/;.mp3?no_dl",
    "description": "talk & speech • MP3 128kbps",
    "votes": 147,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "talk & speech",
    "category": "Genel",
    "isLive": true,
    "website": "https://dostfm.com/",
    "favicon": ""
  },
  {
    "id": "99f2b0aa-60c9-40e6-8556-c9bec390edb4",
    "name": "Denge Welat",
    "url": "https://dengegel-rojavaradio.radioca.st/stream",
    "description": "MP3 96kbps",
    "votes": 153,
    "bitrate": 96,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "kurdish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://denge-welat.org/",
    "favicon": "https://denge-gel.org/wp-content/uploads/2024/02/cropped-logo-removebg-preview-180x180.png"
  },
  {
    "id": "d2d550a5-167e-47e9-afd1-8c6fe9a01c20",
    "name": "dinamo.fm legacy",
    "url": "http://channels.dinamo.fm/legacy-mp3",
    "description": "chillout • deep house • downtempo • MP3 320kbps",
    "votes": 138,
    "bitrate": 320,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "chillout,deep house,downtempo,electronica,house,nu disco,remixes,techno",
    "category": "Genel",
    "isLive": true,
    "website": "http://www.dinamo.fm/",
    "favicon": "https://www.dinamo.fm/favicons/dinamo-legacy-favicon.jpg"
  },
  {
    "id": "5da686e7-99cf-44b7-8e2f-62eac029500c",
    "name": "Doğan 22",
    "url": "http://yayin1.yayindakiler.com:3024/;",
    "description": "classical • AAC+ 128kbps",
    "votes": 134,
    "bitrate": 128,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "classical",
    "category": "Klasik",
    "isLive": true,
    "website": "",
    "favicon": ""
  },
  {
    "id": "0c12afb8-cc4d-4291-9d0f-5dbedc1690a8",
    "name": "Radyo Can",
    "url": "http://yayin2.yayindakiler.com:4174/;stream.mp3",
    "description": "93.4 • radyo can • radyocan • tekirdag • MP3 128kbps",
    "votes": 135,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "93.4,radyo can,radyocan,suleymanpasa,süleymanpaşa,tekirdag,tekirdağ",
    "category": "Genel",
    "isLive": true,
    "website": "http://www.radyocan.net/",
    "favicon": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Radio_icon.svg/32px-Radio_icon.svg.png"
  },
  {
    "id": "14797ffb-2fdd-4a54-9748-e96486914dd2",
    "name": "RADYO AKDENIZ",
    "url": "https://yayin.radyoakdeniz.com/9470/stream",
    "description": "AAC+ 96kbps",
    "votes": 123,
    "bitrate": 96,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://www.radyoakdeniz.com/",
    "favicon": "https://www.radyoakdeniz.com/wp-content/uploads/2024/03/cropped-radyoakdeniz-180x180.png"
  },
  {
    "id": "38909aea-a9a4-45aa-b149-51c3fffdeba1",
    "name": "Doğu Radyo",
    "url": "http://198.7.59.28:8146/",
    "description": "classical • MP3 128kbps",
    "votes": 119,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "classical",
    "category": "Klasik",
    "isLive": true,
    "website": "",
    "favicon": ""
  },
  {
    "id": "4650ba79-390b-4251-bce8-058eb3f39094",
    "name": "S1lhoutte Arabesk FM",
    "url": "https://yayin.radyoarabesk.com.tr:8000/stream",
    "description": "arabesk • Istanbul • AAC+ 128kbps",
    "votes": 135,
    "bitrate": 128,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "arabesk",
    "category": "Genel",
    "isLive": true,
    "website": "https://s1lhouttefm.radiostream123.com/",
    "favicon": ""
  },
  {
    "id": "c745e25e-0af7-431b-a0c2-ee20bd695893",
    "name": "Küpe FM",
    "url": "https://icecast.netmedya.net/kupefm",
    "description": "AAC 128kbps",
    "votes": 125,
    "bitrate": 128,
    "codec": "AAC",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://www.kupefm.com.tr/",
    "favicon": ""
  },
  {
    "id": "cef30f27-1f96-4005-8b7c-e161dba43ccf",
    "name": "Erkam Radyo",
    "url": "https://api-tv5.yayin.com.tr:8002/mp3",
    "description": "islam • islamic • muslim • MP3 128kbps",
    "votes": 115,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "islam,islamic,muslim,religion",
    "category": "Dini",
    "isLive": true,
    "website": "https://www.erkamradyo.com/",
    "favicon": ""
  },
  {
    "id": "dd5c1e07-b1b0-47ee-8115-a83eac808807",
    "name": "Dijital radyo",
    "url": "https://anadolu.liderhost.com.tr:10961/;",
    "description": "MP3 128kbps",
    "votes": 116,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://anadolu.liderhost.com.tr:10961/;",
    "favicon": ""
  },
  {
    "id": "28b60579-045a-4e06-89b6-e85bee30c228",
    "name": "TürküRadyo",
    "url": "https://yayin.turkhosted.com/4591/stream",
    "description": "MP3 64kbps",
    "votes": 105,
    "bitrate": 64,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Müzik",
    "isLive": true,
    "website": "https://turkuradyo.net/",
    "favicon": "https://turkuradyo.net/wp-content/themes/TurkuRadyo/images/logo.png"
  },
  {
    "id": "9056e9ee-3859-11e8-bb9b-52543be04c81",
    "name": "Radyo MODyAn",
    "url": "http://stream.radio.co/s55d598f42/listen",
    "description": "kadife sokak • kadıköy • live show • İstanbul • MP3 128kbps",
    "votes": 100,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "english,turkish",
    "tags": "kadife sokak,kadıköy,live show,moda,music",
    "category": "Müzik",
    "isLive": true,
    "website": "http://modyan.com/",
    "favicon": ""
  },
  {
    "id": "11c8a06a-9d39-45ec-af5c-e9bf98798e69",
    "name": "JoyTürk Akustik",
    "url": "https://27873.live.streamtheworld.com/JOYTURK_AKUSTIK128AAC.aac?/;stream.mp3",
    "description": "pop • Istanbul • AAC+ 128kbps",
    "votes": 108,
    "bitrate": 128,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "pop",
    "category": "Müzik",
    "isLive": true,
    "website": "https://karnaval.com/radyolar/joyturkakustik",
    "favicon": "https://mediacdns.karnaval.com/media/station_media/9/logos/android_default_logo.png"
  },
  {
    "id": "293a2ccf-2cbe-43c4-991f-0abc824715e1",
    "name": "radyozergan",
    "url": "http://yayin1.yayindakiler.com:3194/stream",
    "description": "AAC+ 128kbps",
    "votes": 87,
    "bitrate": 128,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "kurdish,turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "http://www.radyozergan.com/",
    "favicon": ""
  },
  {
    "id": "c7ef0cc3-2ce1-4c4d-9506-ff1ca8d27197",
    "name": "Batı Radyo",
    "url": "https://sslyayin.netyayin.net:10902/",
    "description": "classical • AAC+ 64kbps",
    "votes": 96,
    "bitrate": 64,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "classical",
    "category": "Klasik",
    "isLive": true,
    "website": "",
    "favicon": ""
  },
  {
    "id": "f0be7682-2aab-45b6-b66a-d4380897a6bc",
    "name": "FG 93.8 (Future Generation) mp3 128k",
    "url": "https://edge1.radyotvonline.net/shoutcast/play/fg",
    "description": "chill-out • edm • no ads • AAC 128kbps",
    "votes": 100,
    "bitrate": 128,
    "codec": "AAC",
    "country": "Türkiye",
    "language": "english",
    "tags": "chill-out,edm,no ads,progressive,trance",
    "category": "Genel",
    "isLive": true,
    "website": "https://www.futuregeneration.net/",
    "favicon": "https://i1.sndcdn.com/avatars-6lAdUGxB5DjlvwWt-6IBY7g-t200x200.jpg"
  },
  {
    "id": "d6454808-141d-4872-a5da-5bda389c663b",
    "name": "Number One Best Of",
    "url": "https://n10101m.mediatriple.net/bestof",
    "description": "AAC+ 32kbps",
    "votes": 95,
    "bitrate": 32,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://www.numberone.com.tr/",
    "favicon": ""
  },
  {
    "id": "9ea7ed4e-d777-4e94-bd45-23abfaeaf2d6",
    "name": "Kiss Türk",
    "url": "https://kiss.radyotvonline.net/kissturk",
    "description": "MP3 128kbps",
    "votes": 93,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Müzik",
    "isLive": true,
    "website": "https://kissfm.kissapp.com.tr/",
    "favicon": "https://kissapp.com.tr/content/files/IIMG_BE9E7FDE-27B7-466A-BE72-C344A3DCCD4C.jpg"
  },
  {
    "id": "963c3c6f-0601-11e8-ae97-52543be04c81",
    "name": "AFN 360 Incirlik",
    "url": "http://27823.live.streamtheworld.com/AFNE_ICK_SC",
    "description": "american forces network • MP3 96kbps",
    "votes": 98,
    "bitrate": 96,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "english",
    "tags": "american forces network",
    "category": "Genel",
    "isLive": true,
    "website": "http://www.afneurope.net/AFN-360/",
    "favicon": ""
  },
  {
    "id": "2adbdfbb-1b24-479d-b956-f175c4bb2590",
    "name": "Yeni Radyo Nostaljinin Sesi ",
    "url": "http://51.255.235.165:26113/stream",
    "description": "MP3 64kbps",
    "votes": 78,
    "bitrate": 64,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "",
    "favicon": ""
  },
  {
    "id": "e97c64f6-04c9-4268-a18f-e77fd6ce1416",
    "name": "Aşk FM",
    "url": "http://yayin.asymedya.com:8020/;",
    "description": "pop music • Ankara • AAC+ 32kbps",
    "votes": 85,
    "bitrate": 32,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "pop music",
    "category": "Müzik",
    "isLive": true,
    "website": "https://askfm.com.tr/",
    "favicon": "https://www.radyoreklamankara.com/wp-content/uploads/2016/05/aşk-fm-300x300.png"
  },
  {
    "id": "131f6fc8-1e32-49ab-9a4f-d556db5c7f3e",
    "name": "Kıyı Caz",
    "url": "http://caz.radioca.st/",
    "description": "MP3 128kbps",
    "votes": 80,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://kiyimuzik.com/category/caz/",
    "favicon": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAbYAAABzCAMAAADDhdfxAAAAsVBMVEX///8Ai/8Ah/8Ajf8Aif Ux//q9f9zuf8Ahf/3/P azP 03f8smP Qzf8AjP Cwv9crP8AgP/m8/8Af/85pP9Hqf Cv/8hmv8AfP/y v8Akf/M6P 74P/k8v/e7/9ptf v2P84n//U7P l0f8AeP/H5P9Zsv9Pp/91wf GyP8mlf Y0P m1/ 93P9Cmf9Xs/9ErP99u/9Mov9nr/ iyv96t/9lrP9luf95xP8hoP/D5v9kzvXAAAAKDElEQVR4nO2dCXeiSBCAuUTwiKJGBBQVNInE3DubSf7/D1tMPKqguwt3Mm/DbH3zXt4bsEH9LOijutG070LLP5L17P/63TAVaehHjDlrqwsN86StydrqAmurJaytlrC2WsLaaglrqyWsrZawtlrC2moJa6slrK2WsLZawtpqCWurJaytlrC2WsLaaglrqyWsrZawtlrC2moJa6slrK2WsLZawtpqCWurJaytlrC2WvLF2gIbEFQp4cIS/LupSAVtyaYHGHePNpLGaXP6sdVdXPdPNBP6/HYLFLhufR7bXYMTTr/iY/5p0NriFxNwYW6Pe9qdi8Nm/XLwsWmdWcfj6WaDPv96CQuknxvdlnU8YTj 9Q/550Fqm83B96pb5sI97mp3jrusvbagZ4AXX5LhFvTA0Y2X HOr2zodxex9yef8w6C02dhamJ6s5dqAoU9tWuSD11 k1OkjUbCxNhJCm910gDUdWRNqC8bAg3VNhFvQgMHZP7yatVGotdlj8LXm1lqocijSpk3PCbf4TXgrZG0USm3ozqPrWQNX6aG2x4M2uwlKGP2Z6uR51QME23N02s7a1Ki0FayFvUJDTBhtsKKSf kL1clnI/jS3vECzNooFNpcsIrC7vsbF4NRrM2ew3C7UrWgF CV1nJ9OjNrI5Brc1sh0vZUEiDWpi06oJR5Jz 3DYPtoglPzdrUSLW5rQxKcwTVTIk2 wWFm1sqd2ABr8EZ6A1hbRRSbSmMGd2ZCzoYJdq0LRRurssF91xCbVAva6OQaStYexTdomTagmsUbrJTT6E1sw32sDYKibaFT1uTatNuTVDYikRltUKwXcI9rI1CrK0N28y6g5yckGoLljDcHsRnjlCv2RbuYm0UQm3TDvpKJdbk2rQujFVD3MN1BZvab2gXa6MQaVujWNOl/fhybQE8gvUqKhzB5oVxi/axNgqBtmiJOiKvZfcmhTbtFh4iFHmHfWCWj uprI2irK1oTV6BV2gL4HCp3iyXjWBN1ejinayNoqQtGiFrz4qcAIU2bQOP4pfDrQcqm1ZW6HBmbRRFbQm2tlRlcqi0DVCHcumrT57hqPamsBdp46QEAQVt8TW0ZvltVVmVNg1mJ jL4v2xASskWTEYobYL1iYAaQviPqr5Z4p YI3QFvuKZKDkGux0xsVuS442CqhtnMAxl7wGuFCXVWpzeyCdoZidkKJgK1V6WBsF0Kb3H2GnVKl V0KpTUtgh3LYgrviF3hnK48tsDYKqA1J2yUaEGXV2oIxDLd DHYtYLCF5Ssxa6NoFFyhcCvW8AqoteVNMxBTIUgGms1BdcWYl0uyNgqVNt18V5YltAUw7csA4XZHBBtrI1Fq00fKuRSENm2Nwm1x2Gw3UXJkXC7I2ijU2i5KdXMIpc1 Qpnih66QNaqriDIpWRuFWpuVLRRlKW3aHQq3/dWwQt4ya6NQa9N1VTo41DYSaRug3Lv9k49QTcVsiMKZe0koRNpgjcEcyycXktpw7l340b/p9sSZyBDWRiHQNoepdlYmT OntQ1Q7l1z9wvAnV7i7n3WRlHSZl3Z O4zqjRMKtampaj6sTvSBh7bFw/msTaKojZjl6SVoHEA6ZTuCtrsPjz2q6vZviQTGcLaKArajLcPRws0lzeVtAIqaNNQRnqYaF34g8gko3msjQJrM/zPyHLHYKPlC1rEO6pos9F46I2Gsov6kjfF2iiQNuvt0CSO4YCYIc5uraRN68ITdG5gsJmyQVjWRoG0LU NtDasujst4WWykrbBEoUz/JFcSoqwNhKgDc4wwzk6eiis8VXShlNdITgTGcLaKKQzbmawDmiNRI3uatpsnCwLfiXS/k7WRiGflrhGl0lRuxhpk0/S3qDFFk6nu5WWYG0UiknAXTSRSVBXr6jNxrNSDyV8ea8Za6NQaAse4bjYc7kVUFGb9lMUbqqhc9ZGoVopIUFh0izdiqpqi0XhlklvhqyNRrkuSYq6NEp9ylW1aTflcBPeLA wNgr1cjJX0FtpkKWytqQcbpmk5 UD1kahXrwJjbLoxWn3lbUFqHPkI9gUw3isjYZYKg0u FLIUT1DG56D HEo6WjQDtZGQWjDQ2 F TfVtQV4yTVqfV/WRkGtJxnDlXqsOZJTXRvO1pJ1lh1hbRTk6q146K0lW0 S0IZy74r6S7A2ClJbgOZ9 jCH AxtboqCbaF U6yNgl7iOkF5BTCJ AxtA7h2rzATGcLaKCosKL9Aq5T04BLXlbXhtP W8rVYm/507kf6P1BBm4uH3k5D0tW12c1zVlBmbSRVnroxuwTarCVYp7Wqtgjl3ZGPB2BtFJUeljKF3/ppUZ/K2lz0dIDS/Pvy61kbQc9wDnhzaRt4YzmAw/jmIjxtk2V3fRCjBSbpOobb8E5H/nHmJ/pfEHVPTOVZArfgZZtDDkgMtm5VfYxwbRmro25ql9/VeR I SpstJLT/L9 O0w1unDuvSwTmfn9BJUezbbHPY3 GHr48tveFKPZSSI3E9w9jdeq2cGY7THYjPvxbYVnujH/juDux3I5ln3BwdjzvDCtHHCHNZEtR7VcHvOrDHphXgEfimd6asHTxLAMTzYPJ7hbYKHTfcvQcF4SzV2k8voq8yskL4bnOfk/4aqEwdgxPCt0vGwh/P4XoY6fqrJfE9kxn2Za8MO0sr/Y229g uwNs3E67nhep1W6EiY/cqfNu3UjHApXUVh3ht7xqYc73ndNbctw/NTWZi/5j8FTP66I TfYm3DozKNAC5Ke5 l/t1FoDFpLa2jeBbsBtHBolqd159Yy33HuT/3Nc8uyHKfTi1wtunY83c jmOzdYs4i3twbE vwPN6pNTHM5020/ 9g2rzXndV BV23pXtWcbWZbbjK2rOroae/7i UkW9ZnYc0zl94mxkTPx6kjidfNZs5lyDqjnRvtQLrx8ejVV430bPlw8PDo28aeT1ldXXsMx7n 9AqyIMHZ7XrunI33tDJPh/0HMziQbCT 37t5Nbsne Jp4snzDHVuX29 Xlz9RY6k9VqaL2iQHC3HW Y28n/fP69hLWUvHLiDC/fP6y49vvDcOXtgyzyJ95Qf30/3BoH26XnWJPl58O5G3nIEuPbDMXtKK8W5lYussub93IQRDejUDcMw9Kzx25hdGYb7uLP8UeXb508Tp3RaUW8rp5bnjjL15vX16vOcOLlodo8WIx 8lXyCwjiJEkG0uuW/T5tt6eJYP/s5zKzcul5RFr3V6i9YG/uL/JK52QynOR7DcPsc1v7  Am281Nc7y5fS 1FYJ28/o C00zzJ7/7nF81Qc3nm7TdDud5ZE6UCYiM98He7YPwSCO0maF4VHmG2A3 k tNKf11F SyZHMN2HdcYwLM fCcAxBlwrzHUFPW dgqwvxEi65S2UiM98DtwHXkyczkZnvwewx6xzx/4hg wfBk7e iXC8NQAAAABJRU5ErkJggg=="
  },
  {
    "id": "ddf94722-dd93-4fb5-ac19-ad42649a30e1",
    "name": "Serhat FM 91.5",
    "url": "http://yayin.serhatfm.com:9150/stream",
    "description": "Kırklareli • MP3 80kbps",
    "votes": 86,
    "bitrate": 80,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://serhatfm.com/",
    "favicon": ""
  },
  {
    "id": "cc06c583-3875-4d75-8b90-383c310f1ba8",
    "name": "KIYI Muzik",
    "url": "https://kiyi.radioca.st/stream",
    "description": "MP3 320kbps",
    "votes": 85,
    "bitrate": 320,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://kiyimuzik.com/radyo/",
    "favicon": ""
  },
  {
    "id": "42d185d7-3ae2-4637-8798-bc61dc6f91a9",
    "name": "NUMBER ONE LOUNGE",
    "url": "https://n10101m.mediatriple.net/lounge",
    "description": "AAC+ 128kbps",
    "votes": 80,
    "bitrate": 128,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://n10101m.mediatriple.net/lounge",
    "favicon": ""
  },
  {
    "id": "8f6ffefd-5371-4216-b503-099c7ce2128b",
    "name": "Radyo S",
    "url": "http://icecast.netmedya.net/radyos",
    "description": "dance • dj mix • hits • MP3 192kbps",
    "votes": 76,
    "bitrate": 192,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "dance,dj mix,hits,house",
    "category": "Genel",
    "isLive": true,
    "website": "http://radyos.com.tr/",
    "favicon": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Radio_icon.svg/32px-Radio_icon.svg.png"
  },
  {
    "id": "dc8dcd60-8c02-49ab-b2bc-47a4599ae624",
    "name": "Mega Ask FM",
    "url": "https://embed.tawk.to/_s/v4/assets/audio/chat_sound.mp3",
    "description": "hits • oldies • pop",
    "votes": 71,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "hits,oldies,pop,turkish music",
    "category": "Müzik",
    "isLive": true,
    "website": "https://mega-ask.com.tr/",
    "favicon": ""
  },
  {
    "id": "98fcbf0c-8bd7-480d-8af3-6ab5dbb1ba9b",
    "name": "Radyo Mori",
    "url": "https://amed.ozelip.com/8040/stream",
    "description": "MP3 64kbps",
    "votes": 68,
    "bitrate": 64,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "kurdi,kurdish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://amed.ozelip.com/",
    "favicon": ""
  },
  {
    "id": "8808a63f-0709-4dfb-83f8-5edd8b666d15",
    "name": "Fakir Fm",
    "url": "https://live.radyositesihazir.com/1025/stream/",
    "description": "MP3 128kbps",
    "votes": 67,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://www.fakirfm.com/",
    "favicon": "https://www.fakirfm.com/favicon.ico"
  },
  {
    "id": "c9e14543-dbaf-4173-9d3a-68344f1a1776",
    "name": "AÇS Radyo",
    "url": "https://ip169.ozelip.com:10838/",
    "description": "international • AAC+ 64kbps",
    "votes": 73,
    "bitrate": 64,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "international",
    "category": "Genel",
    "isLive": true,
    "website": "https://acsradyo.com/",
    "favicon": ""
  },
  {
    "id": "d5fb7ff2-4b30-4f0f-a66f-c44a480337ec",
    "name": "Loops Radio Progressive",
    "url": "https://progressive.ozelip.com/7670/stream",
    "description": "Istambul • MP3 320kbps",
    "votes": 71,
    "bitrate": 320,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://loopsradio.com/radiochannel/loops-radio-progressive-house-station/",
    "favicon": "https://loopsradio.com/wp-content/uploads/2023/09/cropped-loopsradiofaviconred-180x180.png"
  },
  {
    "id": "4400ded3-62df-40d9-b1fe-9dfe39cadc12",
    "name": "Loops Radio House Station",
    "url": "https://loopsdeep.ozelip.com/7806/stream",
    "description": "house • Istambul • MP3 128kbps",
    "votes": 69,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "english/,turkish",
    "tags": "house",
    "category": "Genel",
    "isLive": true,
    "website": "https://loopsradio.com/radiochannel/loops-radio-house-station/",
    "favicon": "https://loopsradio.com/wp-content/uploads/2023/09/cropped-loopsradiofaviconred-180x180.png"
  },
  {
    "id": "1d1fd095-2d1b-43f4-be0e-de834631ec30",
    "name": "Bizim Radyo ",
    "url": "https://ip132.ozelip.com:7017/",
    "description": "talk & speech • MP3 64kbps",
    "votes": 68,
    "bitrate": 64,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "talk & speech",
    "category": "Genel",
    "isLive": true,
    "website": "https://www.bizimradyo.com/",
    "favicon": ""
  },
  {
    "id": "5f5eeda9-129f-11ea-a87e-52543be04c81",
    "name": "Radio Wanderlust",
    "url": "http://radyo.yayin.com.tr:5898/",
    "description": "journey • travel • traveler • AAC+ 192kbps",
    "votes": 62,
    "bitrate": 192,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "english",
    "tags": "journey,travel,traveler,wanderlust",
    "category": "Genel",
    "isLive": true,
    "website": "https://www.radiowanderlust.com/",
    "favicon": ""
  },
  {
    "id": "f6bed2c2-37b4-4e57-8beb-bbcc9b3bbf11",
    "name": "Radyo Maranata",
    "url": "http://medya.radyomaranata.com:8005/live",
    "description": "MP3 128kbps",
    "votes": 61,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "http://radyomaranata.com/",
    "favicon": ""
  },
  {
    "id": "86012ae9-d1a4-409b-97c4-df67c1cd0301",
    "name": "Marmaris Yacht Marin FM",
    "url": "https://radio.guventechnology.com:7003//stream/radyomarin",
    "description": "Marmaris • AAC+ 128kbps",
    "votes": 63,
    "bitrate": 128,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://yachtmarinfm.com/",
    "favicon": ""
  },
  {
    "id": "0dc34aa4-d185-413f-8c04-5763bf2ec653",
    "name": "Radyo Sinerji",
    "url": "https://radio.guventechnology.com/9994/stream",
    "description": "Istanbul • MP3 128kbps",
    "votes": 65,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://www.radyosinerji.com/",
    "favicon": ""
  },
  {
    "id": "5729f872-934d-4e28-856e-6b7ae1808863",
    "name": "Loops Radio Elektronica Station",
    "url": "https://ssl22.radyotelekom.com/8232/stream",
    "description": "elektronik • Istambul • MP3 128kbps",
    "votes": 67,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "english uk,turkish",
    "tags": "elektronik",
    "category": "Genel",
    "isLive": true,
    "website": "https://loopsradio.com/radiochannel/loops-radio-electronica-station",
    "favicon": "https://i.postimg.cc/XYRRHwry/android-chrome-512x512.png"
  },
  {
    "id": "5e5b4c7f-716d-42bb-9231-0209c81037e9",
    "name": "Süper 2 FM",
    "url": "https://28513.live.streamtheworld.com:443/SUPER2_SC",
    "description": "hits • pop • turkish music • MP3 64kbps",
    "votes": 60,
    "bitrate": 64,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "hits,pop,turkish music",
    "category": "Müzik",
    "isLive": true,
    "website": "https://karnaval.com/radyolar/super2",
    "favicon": ""
  },
  {
    "id": "3dfe8d72-9ba4-47f2-9f57-a16cd5b273df",
    "name": "Radyo Alaturka",
    "url": "https://yayin.jumboserver.net:9100/stream",
    "description": "AAC 128kbps",
    "votes": 63,
    "bitrate": 128,
    "codec": "AAC",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://radyoalaturka.com.tr/index?0",
    "favicon": "https://radyoalaturka.com.tr/site/assets/img/alaturkaLogo.png"
  },
  {
    "id": "7f4814fc-09f6-4be0-ab7d-6b9320ff3538",
    "name": "Emek radyo",
    "url": "http://yayin1.radyohizmeti.com:8585/;",
    "description": "MP3 128kbps",
    "votes": 55,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "kurdish,turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://emekradyo.net/",
    "favicon": ""
  },
  {
    "id": "b7b5c956-cceb-416e-9686-789956cc41dc",
    "name": "BesteFM",
    "url": "https://server35971.streamplus.de/stream.mp3",
    "description": "hiphop • pop • rap • Istanbul • MP3 128kbps",
    "votes": 56,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "hiphop,pop,rap",
    "category": "Müzik",
    "isLive": true,
    "website": "http://www.bestefm.de/",
    "favicon": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Radio_icon.svg/32px-Radio_icon.svg.png"
  },
  {
    "id": "1fd7925e-09ac-42b3-b560-f4948fa8bfd1",
    "name": "Elazığ Mavi Radyo",
    "url": "https://yayin.turkhosted.com/6066/stream",
    "description": "MP3 128kbps",
    "votes": 57,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "türkisch",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://maviradyo.net/",
    "favicon": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Radio_icon.svg/32px-Radio_icon.svg.png"
  },
  {
    "id": "241fc380-b6ac-49d7-919a-c678fcdb6568",
    "name": "Radyo Yol",
    "url": "https://radyo.yayin.com.tr:5932/;",
    "description": "MP3 128kbps",
    "votes": 50,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://radyoyol.com.tr/",
    "favicon": ""
  },
  {
    "id": "b4c64aa8-9bf1-4015-bc8d-7e10ff1edce9",
    "name": "Loops Radio Techno",
    "url": "https://ip179.ozelip.com/7688//asistan/stream/",
    "description": "Istambul • MP3 128kbps",
    "votes": 55,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://loopsradio.com/radiochannel/loops-radio-techno-station/",
    "favicon": "https://loopsradio.com/wp-content/uploads/2023/09/cropped-loopsradiofaviconred-180x180.png"
  },
  {
    "id": "1afbaf0c-c5d7-4944-833b-aab9ac97d250",
    "name": "DanceLand Anthems",
    "url": "https://likeradiostream.com/dancelandanthems",
    "description": "MP3 128kbps",
    "votes": 53,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://like.radio/danceland-anthems/",
    "favicon": "https://like.radio/favicon.ico"
  },
  {
    "id": "60f46e8b-c57f-4ef0-8aea-be92dddfca43",
    "name": "Mayday Records",
    "url": "https://stream.maydayrecords.net/radio/8000/maydayrecords.mp3",
    "description": "electronic • progressive house • tech house • MP3 256kbps",
    "votes": 52,
    "bitrate": 256,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "english uk,turkish",
    "tags": "electronic,progressive house,tech house",
    "category": "Genel",
    "isLive": true,
    "website": "https://maydayrecords.net/",
    "favicon": "https://i.postimg.cc/ZnsgHRtW/android-chrome-512x512.png"
  },
  {
    "id": "e211532e-a87f-42d9-907c-f2fa08898348",
    "name": "MEGA SİTE",
    "url": "http://yayin.netradyom.com:7900/;stream.mp3",
    "description": "http://yayin.netradyom.com:7900/;stream.mp3 • AAC+ 32kbps",
    "votes": 49,
    "bitrate": 32,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "http://yayin.netradyom.com:7900/;stream.mp3",
    "category": "Genel",
    "isLive": true,
    "website": "http://yayin.netradyom.com:7900/;stream.mp3",
    "favicon": ""
  },
  {
    "id": "3d5b7525-7b92-4a2b-8a00-d502917c3761",
    "name": " GİMSA RADYO",
    "url": "http://yayin1.canliyayin.org:9482/stream",
    "description": "Ankara • MP3 128kbps",
    "votes": 49,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://www.gimsa.com.tr/radyo.php",
    "favicon": "https://www.gimsa.com.tr/images/apple-touch-icon.png"
  },
  {
    "id": "1c5e50a7-ae07-4aae-b9d8-e167c2c2f5ec",
    "name": "radyo megasite",
    "url": "http://mega.netradyom.com:7900/radio.mp3",
    "description": "http://mega.netradyom.com:7900/listen.pls • AAC+ 32kbps",
    "votes": 41,
    "bitrate": 32,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "türkisch",
    "tags": "http://mega.netradyom.com:7900/listen.pls",
    "category": "Genel",
    "isLive": true,
    "website": "http://mega.netradyom.com:7900/listen.pls",
    "favicon": ""
  },
  {
    "id": "969b4ba1-885c-475f-bcc3-4f1e8f3661f0",
    "name": "oyunpiyat",
    "url": "https://yayin.hostwin.net/8888/stream%20%20oyunpiyatfm",
    "description": "karışık • MP3 128kbps",
    "votes": 46,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "karışık",
    "category": "Genel",
    "isLive": true,
    "website": "https://yayin.hostwin.net/8888/stream%20%20oyunpiyatfm",
    "favicon": ""
  },
  {
    "id": "f21b4940-2b6e-4436-b30f-fe16ce46f15a",
    "name": "X Radio",
    "url": "https://stream.xradio.com.tr:8770/stream",
    "description": "turkısh rap • AAC+ 128kbps",
    "votes": 44,
    "bitrate": 128,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "turkısh rap",
    "category": "Genel",
    "isLive": true,
    "website": "https://www.xradio.com.tr/",
    "favicon": "https://www.xradio.com.tr/favicon.ico"
  },
  {
    "id": "5ce39eb0-54da-4b6c-890b-e83c4a0ca228",
    "name": "Arkadas Radyo",
    "url": "http://yayin2.yayindakiler.com:4134/;stream.nsv",
    "description": "hits • pop • turkish music • AAC+ 64kbps",
    "votes": 37,
    "bitrate": 64,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "hits,pop,turkish music",
    "category": "Müzik",
    "isLive": true,
    "website": "https://arkadasradyo.com.tr/",
    "favicon": ""
  },
  {
    "id": "d35ed8b1-871b-47e9-8df0-cfb4a094095b",
    "name": "Radyo 2000 Erzincan",
    "url": "https://radyo.yayindakiler.com:3030/stream?/;stream.mp3",
    "description": "MP3 128kbps",
    "votes": 39,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "http://www.2000radyo.com/",
    "favicon": ""
  },
  {
    "id": "1020f3df-3507-476a-85ca-152e03cb75ff",
    "name": "Radyo Nida",
    "url": "https://anadolu.liderhost.com.tr/8106/stream",
    "description": "ilahi • islam • muslim • Bursa • MP3 128kbps",
    "votes": 40,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish,turkçe",
    "tags": "ilahi,islam,muslim,turk",
    "category": "Dini",
    "isLive": true,
    "website": "https://radyonida.com.tr/",
    "favicon": "https://radyonida.com.tr/dist/img/radyo-nida.jpg?2"
  },
  {
    "id": "93be144b-054e-4669-b0b0-44d1f05cbb82",
    "name": "Giresun FM",
    "url": "http://yayin.canliyayin.org:9482/;",
    "description": "pop • turkish music • MP3 128kbps",
    "votes": 35,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "pop,turkish music",
    "category": "Müzik",
    "isLive": true,
    "website": "https://giresunfm.com.tr/",
    "favicon": ""
  },
  {
    "id": "ce26d234-1413-4a97-8f7d-5a476bacf104",
    "name": "Apacik Radyo",
    "url": "http://stream.34bit.net/ar.aac",
    "description": "community radio • world music • AAC+ 128kbps",
    "votes": 35,
    "bitrate": 128,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "english,greek,turkish",
    "tags": "community radio,world music",
    "category": "Müzik",
    "isLive": true,
    "website": "http://www.apacikradyo.com.tr/",
    "favicon": "https://apacikradyo.com.tr/logo1024"
  },
  {
    "id": "25fba87c-ddc8-409a-8474-4ffbac809c59",
    "name": "Radio Glamorize",
    "url": "https://live.radioglamorize.com/stream1",
    "description": "electronic music • progressive house • Istanbul • MP3 128kbps",
    "votes": 38,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "english,english uk,turkish",
    "tags": "electronic music,progressive house",
    "category": "Müzik",
    "isLive": true,
    "website": "https://radioglamorize.com/",
    "favicon": "https://radioglamorize.com/wp-content/uploads/2020/05/cropped-sdiavatar2-180x180.png"
  },
  {
    "id": "53b3bd71-643d-4638-8a18-8b21b7bf9e2c",
    "name": "trakyafm",
    "url": "http://trakyafm.canliyayinda.com:9039/",
    "description": "classical • MP3 128kbps",
    "votes": 34,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "classical",
    "category": "Klasik",
    "isLive": true,
    "website": "http://trakyafm.canliyayinda.com:9039/",
    "favicon": ""
  },
  {
    "id": "7ea58b1d-e502-4e03-abb1-65b2408bab2d",
    "name": "Radyo Fıtrat",
    "url": "http://radyofitrat.radyotvonline.net/",
    "description": "islamic • quran • religion • Istanbul • MP3 128kbps",
    "votes": 33,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "islamic,quran,religion",
    "category": "Dini",
    "isLive": true,
    "website": "http://www.radyofitrat.com/",
    "favicon": ""
  },
  {
    "id": "15cc4554-cd2e-4ecb-a28d-163816cc3d9e",
    "name": "Radyo 13",
    "url": "https://radyo.yayindakiler.com:3050/stream?/;stream.mp3",
    "description": "AAC+ 128kbps",
    "votes": 29,
    "bitrate": 128,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "http://www.radyo13.com.tr/",
    "favicon": ""
  },
  {
    "id": "38233bd5-104c-420e-af33-7af24b90ec67",
    "name": "Radyo Göktürk",
    "url": "https://ip231.ozelip.com:8004/;stream.mp3",
    "description": "Turkey • MP3 128kbps",
    "votes": 29,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Müzik",
    "isLive": true,
    "website": "https://www.radyogokturk.com/",
    "favicon": "https://radyogokturk.com/dinle/doc/avatar.jpg"
  },
  {
    "id": "06e0a4f2-107d-41ae-ad24-f57f4005c3ea",
    "name": "Sezen Radyo",
    "url": "http://radyo1.radyo-dinle.tc:8038/",
    "description": "MP3 128kbps",
    "votes": 26,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "http://www.sezenradyo.com/",
    "favicon": ""
  },
  {
    "id": "c49bf5c6-810f-40f4-a0b8-45baa006bf63",
    "name": "Radio Line ",
    "url": "https://online.radioline.fm:8443/stream",
    "description": "eclectic • oldies • pop music • AAC+ 64kbps",
    "votes": 27,
    "bitrate": 64,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "english",
    "tags": "eclectic,oldies,pop music,pop rock,smoothjazz",
    "category": "Müzik",
    "isLive": true,
    "website": "https://radioline.fm/",
    "favicon": "https://radioline.fm/wp-content/uploads/2020/05/radioline_logo.png"
  },
  {
    "id": "6e57a874-b7d9-46f3-9c6d-a2f246049509",
    "name": "Radio Light",
    "url": "http://yayin.radiolight.net:8005/live",
    "description": "MP3 128kbps",
    "votes": 25,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "http://radiolight.net/",
    "favicon": ""
  },
  {
    "id": "c0f5e413-4c6a-4146-90d9-774ef452ee4b",
    "name": "KIYI Turkce",
    "url": "https://kiyiturk.radioca.st/stream",
    "description": "MP3 128kbps",
    "votes": 26,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://kiyimuzik.com/radyo/",
    "favicon": ""
  },
  {
    "id": "d3714737-f527-451f-a93d-a66368e188b0",
    "name": "Erzincan Nostalji Radyo ",
    "url": "https://erzincannostalji.ozelip.com/8238/stream",
    "description": "MP3 128kbps",
    "votes": 24,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "türkisch",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://erzincannostalji.ozelip.com/8238/stream",
    "favicon": "null"
  },
  {
    "id": "525136b0-b913-42c6-9e28-e3c332cbaaa8",
    "name": "Türkiyem FM",
    "url": "https://server7.streamserver24.com/proxy/turkiyemfm?mp=/stream",
    "description": "traditional music • MP3 128kbps",
    "votes": 23,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "traditional music",
    "category": "Müzik",
    "isLive": true,
    "website": "https://turkiyemfm.com/",
    "favicon": "https://turkiyemfm.com"
  },
  {
    "id": "2e728efe-5d69-410b-a5d2-e987ca66c09f",
    "name": "Konya İsra FM",
    "url": "https://yayin2.canliyayin.org:8210/;stream",
    "description": "islam • islamic • islma • Konya • MP3 128kbps",
    "votes": 22,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "islam,islamic,islma,konya,turk",
    "category": "Dini",
    "isLive": true,
    "website": "https://www.israfm.com/",
    "favicon": "https://www.canliradyodinle.fm/wp-content/uploads/isra-fm.jpg"
  },
  {
    "id": "fcbf07d8-d3b3-4d9f-839a-3cfea3391b35",
    "name": "Radyo 35",
    "url": "https://yayin.turkhosted.com/6012/stream",
    "description": "pop • türkçe • izmir • AAC+ 128kbps",
    "votes": 22,
    "bitrate": 128,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "tr,turkish",
    "tags": "pop,türkçe",
    "category": "Müzik",
    "isLive": true,
    "website": "https://www.radyo35.com/",
    "favicon": "https://www.radyo35.com/img/logo.png"
  },
  {
    "id": "0e086ad4-2575-4437-b6db-796770537ea5",
    "name": "Radyo Karabalı",
    "url": "https://radyokarabali.ozelip.com:9884/;",
    "description": "MP3 64kbps",
    "votes": 22,
    "bitrate": 64,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "türkisch",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://radyokarabali.net/",
    "favicon": "null"
  },
  {
    "id": "58424e47-51db-41e6-9042-efcbdc9c1a2d",
    "name": "Diyarbakır Çağrı FM",
    "url": "https://live.cagrifm.com.tr/cagrifm",
    "description": "ilahi • islam • islamic • Bursa • MP3 256kbps",
    "votes": 23,
    "bitrate": 256,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "ilahi,islam,islamic",
    "category": "Dini",
    "isLive": true,
    "website": "https://www.cagrifm.com.tr/",
    "favicon": ""
  },
  {
    "id": "461458d7-6472-4bf1-adca-d33705dad718",
    "name": "Radyo Alevi Canlar",
    "url": "https://alevifm.80.yayin.com.tr/",
    "description": "AAC+ 128kbps",
    "votes": 18,
    "bitrate": 128,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://alevifm.com.tr/",
    "favicon": "null"
  },
  {
    "id": "18bb0468-5bca-40cc-bc22-a1e5635ac7e8",
    "name": "S1lhoutte - Karadeniz FM",
    "url": "http://yayin.liderhost.net:8028/",
    "description": "karadeniz • Istanbul • AAC+ 96kbps",
    "votes": 15,
    "bitrate": 96,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "karadeniz",
    "category": "Genel",
    "isLive": true,
    "website": "http://yayin.liderhost.net:8028/",
    "favicon": ""
  },
  {
    "id": "9cf8015c-8b88-476c-a2b8-093e52d75012",
    "name": "Radyo 9",
    "url": "https://radyo.yayin.com.tr:4010/",
    "description": "9 • 99.9 • 99.9 fm • AAC+ 160kbps",
    "votes": 17,
    "bitrate": 160,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "9,99.9,99.9 fm,ankara,aydin,aydın,bölgesel,dokuz,fm,haber,istanbul,izmir,müzik,nazilli,news,pop,pop müzik,radyo,radyo 9,turkey,türk,türkiye,türkçe,ulusal,yerel",
    "category": "Haber",
    "isLive": true,
    "website": "https://www.radyo9.com/",
    "favicon": "https://www.radyo9.com/logo.png"
  },
  {
    "id": "e1480c4f-467f-44ec-8b57-653abdfc7c7e",
    "name": "Radyo Gökçeada",
    "url": "https://radyo.yayin.com.tr:6179/;",
    "description": "90s • aor / slow rock / soft rock (adult-orientated rock e.g. the eagles.) • easy listening • Canakk",
    "votes": 15,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "english,turkish",
    "tags": "90s,aor / slow rock / soft rock (adult-orientated rock e.g. the eagles.),easy listening,jazz,turkish pop",
    "category": "Müzik",
    "isLive": true,
    "website": "https://www.radyogokceada.net/",
    "favicon": "https://www.radyogokceada.net/favicon.ico"
  },
  {
    "id": "b09f14f7-291b-4845-980a-3b44a8926138",
    "name": "Danceland",
    "url": "https://likeradiostream.com/danceland",
    "description": "MP3 128kbps",
    "votes": 21,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://like.radio/danceland-home/",
    "favicon": "https://like.radio/favicon.ico"
  },
  {
    "id": "e15a3233-3781-4056-831e-c07dd5fc60be",
    "name": "Radyo Odtu Easy",
    "url": "https://stream3.radyoodtu.com.tr:8000/easy",
    "description": "easy listening • MP3 128kbps",
    "votes": 12,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "easy listening",
    "category": "Genel",
    "isLive": true,
    "website": "https://radyoodtu.com.tr/",
    "favicon": ""
  },
  {
    "id": "c1b41b98-7a4a-4b2f-8d68-3322fdd428e1",
    "name": "Kıyı Türkçe",
    "url": "https://kiyiturk.radioca.st/",
    "description": "MP3 128kbps",
    "votes": 14,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Müzik",
    "isLive": true,
    "website": "https://kiyimuzik.com/",
    "favicon": ""
  },
  {
    "id": "c16f41f7-668c-409f-aeda-d1d1bb3f1761",
    "name": "Radyo EN",
    "url": "https://yayin2.canliyayin.org:7222/;",
    "description": "ilahi • islam • islamic • Konya • MP3 64kbps",
    "votes": 14,
    "bitrate": 64,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "ilahi,islam,islamic,konya",
    "category": "Dini",
    "isLive": true,
    "website": "https://www.radyoen.com.tr/",
    "favicon": "https://www.radyoen.com.tr/images/radyo-en-logo.png"
  },
  {
    "id": "4b7a7d59-6a9c-4e7f-8807-6ad3c8c614e3",
    "name": "BASER KURAN VE MEAL RADYO",
    "url": "https://s3.free-shoutcast.com/stream/18034",
    "description": "Mersin • MP3 64kbps",
    "votes": 12,
    "bitrate": 64,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Dini",
    "isLive": true,
    "website": "http://baser.org/",
    "favicon": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Radio_icon.svg/32px-Radio_icon.svg.png"
  },
  {
    "id": "8b4a6d48-413e-493f-8d19-5eaa8b9b3bb6",
    "name": "Bayram FM",
    "url": "https://sslyayin.netyayin.net:10962/320.mp3",
    "description": "AAC+ 96kbps",
    "votes": 11,
    "bitrate": 96,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://www.bayramfm.com/",
    "favicon": "https://www.radyodinletv.com/wp-content/uploads/bayram-fm-300x159.jpg"
  },
  {
    "id": "03fe4753-3683-4913-ac9a-b32d260da990",
    "name": "Erkam Radyo 2nd Stream",
    "url": "https://yayin2.canliyayin.org:10910/stream?",
    "description": "MP3 128kbps",
    "votes": 13,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "turkish,turkçe",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://www.erkamradyo.com/",
    "favicon": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Radio_icon.svg/32px-Radio_icon.svg.png"
  },
  {
    "id": "3e71f5fb-643a-4f73-9ba1-c91d3e726d87",
    "name": "Atatürk Airport (LTBA) ATC Tower",
    "url": "http://s1-bos.liveatc.net:80/ltba_s?nocache=2025062706520160691",
    "description": "airport • turkiye • Istanbul",
    "votes": 14,
    "bitrate": 128,
    "codec": "MP3",
    "country": "Türkiye",
    "language": "english,turkish",
    "tags": "airport,turkiye",
    "category": "Müzik",
    "isLive": true,
    "website": "https://www.liveatc.net/play/ltba_s.pls",
    "favicon": "https://i.ibb.co/kgWn5Ht/ATC-Tower.png"
  },
  {
    "id": "926a0629-3096-4755-a3b3-031e78bef5c1",
    "name": "Radio Mydonose",
    "url": "https://29083.live.streamtheworld.com/RADIO_MYDONOSE128AAC.aac?/;stream.mp3",
    "description": "AAC+ 128kbps",
    "votes": 11,
    "bitrate": 128,
    "codec": "AAC",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Genel",
    "isLive": true,
    "website": "https://karnaval.com/radyolar/radiomydonose",
    "favicon": ""
  },
  {
    "id": "7ee088e7-375f-4f1f-bd60-55a3606e9d3f",
    "name": "Mydonose Türk",
    "url": "https://27913.live.streamtheworld.com/MYDONOSE_TURK128AAC.aac?/;stream.mp3",
    "description": "AAC+ 128kbps",
    "votes": 13,
    "bitrate": 128,
    "codec": "AAC+",
    "country": "Türkiye",
    "language": "turkish",
    "tags": "",
    "category": "Müzik",
    "isLive": true,
    "website": "https://karnaval.com/radyolar/mydonoseturk",
    "favicon": ""
  }
];

// Kullanıcının en üste taşınmasını istediği radyoların isimleri:
const TOP_RADIO_NAMES = [
  "TRT FM", "Virgin Radio Türkiye", "Süper FM", "Radyo 7", "Radyo Seymen", "Pal station", "İstanbul FM", "Küpe FM", "Radyo 35", "Radyo ODTU", "Slow Turk", "Elazığ Mavi Radyo"
];

// Sıralama işlemi: önce listedeki radyolar, sonra kalanlar
const topStations = RADIO_STATIONS.filter(r => TOP_RADIO_NAMES.some(name => r.name.trim().toLowerCase() === name.trim().toLowerCase()));
const restStations = RADIO_STATIONS.filter(r => !TOP_RADIO_NAMES.some(name => r.name.trim().toLowerCase() === name.trim().toLowerCase()));

export const RADIO_STATIONS_SORTED: RadioStation[] = [
  ...topStations,
  ...restStations
];

// Statistics
export const RADIO_STATS = {
  totalStations: 200,
  lastUpdated: '2025-06-27T08:45:29.823Z',
  categories: {
    'Genel': 119,
    'Müzik': 46,
    'Kamu': 2,
    'Haber': 4,
    'Dini': 11,
    'Klasik': 18
  },
  topByVotes: [
    { name: 'Radyo Dejavu', votes: 5669 },
    { name: 'Radyo Fenomen', votes: 5279 },
    { name: 'Metro FM', votes: 10349 },
    { name: 'Metro fm turkey', votes: 1153 },
    { name: 'Virgin Radio Türkiye', votes: 17838 },
    { name: 'Joy Fm', votes: 1914 },
    { name: 'Number one', votes: 1777 },
    { name: 'Süper FM', votes: 4908 },
    { name: 'Radyo Fenomen Clubbin', votes: 694 },
    { name: 'TRT FM', votes: 337 }
  ]
};
