export interface RadioStation {
  id: string;
  name: string;
  url: string;
  category: string;
  description?: string;
  country?: string;
  language?: string;
  codec?: string;
  bitrate?: number;
  tags?: string[];
  favicon?: string;
  homepage?: string;
  streamUrl?: string;
  imageUrl?: string;
  isLive?: boolean;
  genre?: string;
  city?: string;
  website?: string;
  votes?: number;
  isGuaranteed?: boolean;
}

export interface Category {
  id: string;
  name: string;
  icon: string;
}

export const CATEGORIES: Category[] = [
  { id: 'all', name: 'Tümü', icon: '📻' },
  { id: 'pop', name: 'Pop', icon: '🎵' },
  { id: 'rock', name: 'Rock', icon: '🎸' },
  { id: 'classical', name: 'Klasik', icon: '🎼' },
  { id: 'folk', name: 'Türk Halk Müziği', icon: '🪕' },
  { id: 'jazz', name: 'Jazz', icon: '🎷' },
  { id: 'news', name: 'Haber', icon: '📰' },
  { id: 'sports', name: 'Spor', icon: '⚽' },
  { id: 'talk', name: 'Sohbet', icon: '🎙️' },
  { id: 'dance', name: 'Dans', icon: '💃' },
  { id: 'hits', name: 'Hit Müzikler', icon: '🔥' },
];

// ⚠️ ÖNEMLİ UYARI: ÇALIŞAN RADYOLAR ⚠️
// Bu dosyada bulunan 4 Power radyosu test edilmiştir ve çalışmaktadır
// Bu radyolara zarar verilmemesi için dikkatli olunmalıdır
// Yedek dosya: WORKING_RADIOS_BACKUP.ts
// Son test tarihi: 24 Haziran 2025
// Durum: ✅ TÜM RADYOLAR ÇALIŞIYOR

// Power FM Group Radyo İstasyonları - Seçili Power Grubu Radyoları
export const RADIO_STATIONS: RadioStation[] = [
  {
    id: 'power-turk',
    name: '⚡ Power Türk',
    url: 'https://listen.powerapp.com.tr/powerturk/mpeg/icecast.audio',
    streamUrl: 'https://listen.powerapp.com.tr/powerturk/mpeg/icecast.audio',
    category: 'pop',
    description: 'Türkçe Pop ve Rock - Power Group',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'MP3',
    bitrate: 128,
    isGuaranteed: true,
    imageUrl: 'https://www.powerturk.com.tr/favicon.ico'
  },
  {
    id: 'power-pop',
    name: '⚡ Power Pop',
    url: 'https://listen.powerapp.com.tr/powerpop/mpeg/icecast.audio',
    streamUrl: 'https://listen.powerapp.com.tr/powerpop/mpeg/icecast.audio',
    category: 'pop',
    description: 'Pop Müzik - Power Group',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'MP3',
    bitrate: 128,
    isGuaranteed: true,
    imageUrl: 'https://www.powerpop.com.tr/favicon.ico'
  },
  {
    id: 'power-love',
    name: '⚡ Power Love',
    url: 'https://listen.powerapp.com.tr/powerlove/mpeg/icecast.audio',
    streamUrl: 'https://listen.powerapp.com.tr/powerlove/mpeg/icecast.audio',
    category: 'pop',
    description: 'Aşk Şarkıları - Power Group',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'MP3',
    bitrate: 128,
    isGuaranteed: true,
    imageUrl: 'https://www.powerlove.com.tr/favicon.ico'  },
  {
    id: 'power-dance',
    name: '⚡ Power Dance',
    url: 'https://listen.powerapp.com.tr/powerdance/mpeg/icecast.audio',
    streamUrl: 'https://listen.powerapp.com.tr/powerdance/mpeg/icecast.audio',
    category: 'dance',
    description: 'Dans Müziği - Power Group',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'MP3',
    bitrate: 128,
    isGuaranteed: true,
    imageUrl: 'https://www.powerdance.com.tr/favicon.ico'
  },  {
    id: 'a-haber',
    name: '📰 A Haber',
    url: 'https://trkvz-radyolar.ercdn.net/ahaberradyo/playlist.m3u8',
    streamUrl: 'https://trkvz-radyolar.ercdn.net/ahaberradyo/playlist.m3u8',
    category: 'news',
    description: 'A Haber Radyosu - Haber ve Güncel Olaylar',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC',
    bitrate: 64,
    votes: 6055,
    isGuaranteed: true,
    imageUrl: 'https://www.ahaber.com.tr/favicon.ico'
  },
  // EN POPÜLER TÜRK RADYO İSTASYONLARI (Radio Browser API'den)
  {
    id: 'arabesk-fm',
    name: '🎵 Arabesk FM',
    url: 'http://yayin.arabeskfm.biz:8042/',
    streamUrl: 'http://yayin.arabeskfm.biz:8042/',
    category: 'folk',
    description: 'Arabesk FM - En Popüler Türk Arabesk Müziği',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'MP3',
    bitrate: 128,
    votes: 24963,
    tags: ['müzik', 'türkçe', 'arabesk'],
    homepage: 'http://www.arabeskfm.biz/'
  },
  {
    id: 'virgin-radio-turkiye',
    name: '🎸 Virgin Radio Türkiye',
    url: 'http://28553.live.streamtheworld.com:3690/VIRGIN_RADIO_SC',
    streamUrl: 'http://28553.live.streamtheworld.com:3690/VIRGIN_RADIO_SC',
    category: 'pop',
    description: 'Virgin Radio Türkiye - Pop ve Rock Müzik',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'MP3',
    bitrate: 64,
    votes: 17833,
    tags: ['pop', 'rock'],
    homepage: 'http://www.virginradioturkiye.com/',
    favicon: 'https://i.karnavalcdn.com/media/site_media/icons/android-icon-192x192.png'
  },
  {
    id: 'best-fm',
    name: '🔥 Best FM',
    url: 'http://46.20.7.126/;stream.mp3',
    streamUrl: 'http://46.20.7.126/;stream.mp3',
    category: 'hits',
    description: 'Best FM - En İyi Hit Müzikler',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'MP3',
    bitrate: 128,
    votes: 15821
  },
  {
    id: 'damar-turk-fm',
    name: '� Damar Türk FM',
    url: 'https://live.radyositesihazir.com:10997/',
    streamUrl: 'https://live.radyositesihazir.com:10997/',
    category: 'folk',
    description: 'Damar Türk FM - Türk Halk ve Damar Müziği',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'MP3',
    bitrate: 128,
    votes: 14408,
    city: 'istanbul bagcılar',
    homepage: 'https://www.damarturkfm.com/',
    favicon: 'https://www.damarturkfm.com/favicon.ico'
  },
  {
    id: 'turkulerle-turkiye',
    name: '🪕 Türkülerle Türkiye',
    url: 'http://37.247.98.8/stream/22/',
    streamUrl: 'http://37.247.98.8/stream/22/',
    category: 'folk',
    description: 'Türkülerle Türkiye - Türk Halk Müziği ve Türküler',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'MP3',
    bitrate: 128,
    votes: 13664,
    tags: ['türkü'],
    homepage: 'https://www.canliradyodinle.fm/radyo-turkulerle-turkiye-dinle.html'
  },
  {
    id: 'radyo-7',
    name: '7️⃣ Radyo 7',
    url: 'http://46.20.3.250/;stream',
    streamUrl: 'http://46.20.3.250/;stream',
    category: 'pop',
    description: 'Radyo 7 - Karışık Pop Müzik',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'MP3',
    bitrate: 128,
    votes: 13505,
    homepage: 'http://www.radyo7.com/',
    favicon: 'https://cdn.kanal7.com/radyo7//application/assets/home/common/images/apple-touch-icon-114x114.png'
  },
  {
    id: 'radyo-siran',
    name: '🎶 Radyo Şiran',
    url: 'https://live.radyositesihazir.com/8078/stream',
    streamUrl: 'https://live.radyositesihazir.com/8078/stream',
    category: 'folk',
    description: 'Radyo Şiran - Türk Halk Müziği',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'MP3',
    bitrate: 128,
    votes: 12711,
    tags: ['folk']
  },
  {
    id: 'metro-fm',
    name: '🚇 Metro FM',
    url: 'http://28943.live.streamtheworld.com:3690/METRO_FMAAC_SC',
    streamUrl: 'http://28943.live.streamtheworld.com:3690/METRO_FMAAC_SC',
    category: 'pop',
    description: 'Metro FM - Türkiye\'nin En Popüler Radyosu',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC+',
    bitrate: 64,
    votes: 10348,
    homepage: 'https://metrofm.com.tr/',
    favicon: 'https://metrofm.com.tr/favicon.ico'
  },
  {
    id: 'ntv-radyo',
    name: '📺 NTV Radyo',
    url: 'http://46.20.3.207/listen.pls',
    streamUrl: 'http://46.20.3.207/listen.pls',
    category: 'news',
    description: 'NTV Radyo - Haber ve Güncel Konular',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC+',
    bitrate: 151,
    votes: 9116,
    tags: ['haber', 'haberler', 'news', 'türkçe'],
    homepage: 'http://www.ntvradyo.com.tr/Home',
    favicon: 'http://www.ntvradyo.com.tr/favicon.ico'
  },
  {
    id: 'power-pop-api',
    name: '⚡ Power POP (Live)',
    url: 'https://listen.powerapp.com.tr/powerpop/128/chunks.m3u8',
    streamUrl: 'https://listen.powerapp.com.tr/powerpop/128/chunks.m3u8',
    category: 'pop',
    description: 'Power POP - 70s, 80s, 90s Pop ve Rock',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC',
    bitrate: 128,
    votes: 9032,
    tags: ['00s', '70s', '80s', '90s', 'pop', 'rock'],
    homepage: 'https://www.powerapp.com.tr/powerpop/',
    favicon: 'https://www.powerapp.com.tr/i/favicov2/apple-icon-120x120.png?v=817'
  },
  {
    id: 'radio-5-turkey',
    name: '5️⃣ Radio 5 Turkey',
    url: 'http://radyo.yayin.com.tr:4108/stream',
    streamUrl: 'http://radyo.yayin.com.tr:4108/stream',
    category: 'hits',
    description: 'Radio 5 Turkey - Top 100 Hit Müzikler',
    country: 'Turkey',
    language: 'English',
    codec: 'AAC+',
    bitrate: 128,
    votes: 8871,
    tags: ['adult contemporary', 'hits', 'non-stop', 'top 100'],
    homepage: 'https://www.radio5.com.tr/',
    favicon: 'http://radio5.com.tr/wp-content/plugins/under-construction-page/themes/images/favicon.png'
  },
  {
    id: 'alem-fm-api',
    name: '🌍 Alem FM (Live)',
    url: 'http://turkmedya.radyotvonline.com/turkmedya/alemfm.stream/playlist.m3u8',
    streamUrl: 'http://turkmedya.radyotvonline.com/turkmedya/alemfm.stream/playlist.m3u8',
    category: 'pop',
    description: 'Alem FM - Türkçe ve Yabancı Müzik Karışımı',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC',
    bitrate: 128,
    votes: 8133,
    homepage: 'https://www.alemfm.com/',
    favicon: 'https://www.alemfm.com/assets/img/alemfm-apple-touch-icon.png'
  },
  {
    id: 'kral-turk-fm',
    name: '👑 Kral Türk FM',
    url: 'https://live.radyositesihazir.com/8032/stream',
    streamUrl: 'https://live.radyositesihazir.com/8032/stream',
    category: 'pop',
    description: 'Kral Türk FM - Türkçe Pop Müzik',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'MP3',
    bitrate: 128,
    votes: 7889
  },
  {
    id: 'ankara-havalari',
    name: '🏛️ Ankara Havaları',
    url: 'http://37.247.98.8/stream/30/',
    streamUrl: 'http://37.247.98.8/stream/30/',
    category: 'folk',
    description: 'Ankara Havaları - Ankara ve Anadolu Türküleri',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'MP3',
    bitrate: 128,
    votes: 7627,
    tags: ['folk']
  },
  {
    id: 'altin-sarkilar',
    name: '🥇 Altın Şarkılar',
    url: 'http://37.247.98.8/stream/25/',
    streamUrl: 'http://37.247.98.8/stream/25/',
    category: 'hits',
    description: 'Altın Şarkılar - Nostaljik Hit Şarkılar',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'MP3',
    bitrate: 128,
    votes: 7299,
    tags: ['golden oldies', 'retro'],
    homepage: 'http://www.radyohome.com/#altinsarkilar'
  },
  {
    id: 'baba-radyo',
    name: '👴 Baba Radyo',
    url: 'http://46.20.7.116/',
    streamUrl: 'http://46.20.7.116/',
    category: 'folk',
    description: 'Baba Radyo - Türk Halk Müziği ve Nostalji',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC+',
    bitrate: 64,
    votes: 6772,
    tags: ['folk']
  },
  {
    id: 'radyo-dejavu',
    name: '⏮️ Radyo Dejavu',
    url: 'http://radyodejavu.canliyayinda.com:8054/',
    streamUrl: 'http://radyodejavu.canliyayinda.com:8054/',
    category: 'hits',
    description: 'Radyo Dejavu - Nostaljik Müzikler',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC+',
    bitrate: 64,
    votes: 5667,
    homepage: 'http://www.radyodejavu.com/'
  },
  {
    id: 'dinamo-fm-sleep',
    name: '😴 Dinamo FM Sleep',
    url: 'http://channels.dinamo.fm/sleep-mp3',
    streamUrl: 'http://channels.dinamo.fm/sleep-mp3',
    category: 'classical',
    description: 'Dinamo FM Sleep - Rahatlatıcı Uyku Müzikleri',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'MP3',
    bitrate: 320,
    votes: 5554,
    city: 'Istanbul',
    tags: ['ambient', 'chillout', 'lullaby', 'relaxing', 'sleep', 'zen'],
    homepage: 'http://www.dinamo.fm/',
    favicon: 'https://www.dinamo.fm/favicons/dinamo-sleep-favicon.jpg'
  },
  {
    id: 'radyo-vatan-turku',
    name: '🇹🇷 Radyo Vatan Türkü',
    url: 'http://95.0.173.195:9000/turku',
    streamUrl: 'http://95.0.173.195:9000/turku',
    category: 'folk',
    description: 'Radyo Vatan Türkü - Vatan Türküleri',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'MP3',
    bitrate: 128,
    votes: 5363
  },
  {
    id: 'radyo-fenomen',
    name: '⭐ Radyo Fenomen',
    url: 'https://live.radyofenomen.com/fenomen/128/icecast.audio',
    streamUrl: 'https://live.radyofenomen.com/fenomen/128/icecast.audio',
    category: 'pop',
    description: 'Radyo Fenomen - Modern Türkçe Pop Müzik',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC+',
    bitrate: 56,
    votes: 5269,
    tags: ['turkey'],
    homepage: 'https://www.radyofenomen.com/'
  },
  {
    id: 'super-fm',
    name: '🌟 Süper FM',
    url: 'http://28973.live.streamtheworld.com:3690/SUPER_FMAAC_SC',
    streamUrl: 'http://28973.live.streamtheworld.com:3690/SUPER_FMAAC_SC',
    category: 'pop',
    description: 'Süper FM - Pop Müzik',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC+',
    bitrate: 64,
    votes: 4905,
    tags: ['pop']
  },
  {
    id: 'radyo-seymen',
    name: '🎭 Radyo Seymen',
    url: 'https://yayin.radyoseymen.com.tr:1070/stream',
    streamUrl: 'https://yayin.radyoseymen.com.tr:1070/stream',
    category: 'folk',
    description: 'Radyo Seymen - Türk Sanat ve Halk Müziği',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC+',
    bitrate: 128,
    votes: 4293,
    homepage: 'https://www.radyoseymen.com.tr/'
  },
  {
    id: 'kral-fm-official',
    name: '👑 Kral FM',
    url: 'https://dygedge2.radyotvonline.net/kralfm/playlist.m3u8',
    streamUrl: 'https://dygedge2.radyotvonline.net/kralfm/playlist.m3u8',
    category: 'pop',
    description: 'Kral FM - Türkiye\'nin Kralı',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC',
    bitrate: 128,
    votes: 759,
    homepage: 'https://www.kralmuzik.com.tr/radyo/kral-fm#',
    favicon: 'https://cdn1.kralmuzik.com.tr/media/content/19-05/17/kralfm.png'
  },
  {
    id: 'joy-fm',
    name: '😊 Joy FM',
    url: 'http://28513.live.streamtheworld.com:3690/JOY_FMAAC_SC',
    streamUrl: 'http://28513.live.streamtheworld.com:3690/JOY_FMAAC_SC',
    category: 'pop',
    description: 'Joy FM - Neşeli Müzikler',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC+',
    bitrate: 64,
    votes: 1911,
    tags: ['international']
  },
  {
    id: 'joy-turk',
    name: '🇹🇷 Joy Türk',
    url: 'https://27913.live.streamtheworld.com:443/JOY_TURK_SC',
    streamUrl: 'https://27913.live.streamtheworld.com:443/JOY_TURK_SC',
    category: 'pop',
    description: 'Joy Türk - Türkçe Pop Müzik',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'MP3',
    bitrate: 64,
    votes: 1825
  },
  {
    id: 'number-one-fm',
    name: '1️⃣ Number One FM',
    url: 'https://n10101m.mediatriple.net/numberone',
    streamUrl: 'https://n10101m.mediatriple.net/numberone',
    category: 'hits',
    description: 'Number One - En İyi Hit Müzikler',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC+',
    bitrate: 32,
    votes: 1774,
    homepage: 'https://numberone.com.tr/'
  },
  {
    id: 'diyanet-radyo',
    name: '🕌 Diyanet Radyo',
    url: 'https://eustr73.mediatriple.net/videoonlylive/mtikoimxnztxlive/broadcast_5e3c1171d7d2a.smil/playlist.m3u8',
    streamUrl: 'https://eustr73.mediatriple.net/videoonlylive/mtikoimxnztxlive/broadcast_5e3c1171d7d2a.smil/playlist.m3u8',
    category: 'talk',
    description: 'Diyanet Radyo - Dini Yayınlar',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC',
    bitrate: 140,
    votes: 1615,
    homepage: 'https://www.diyanetradyo.com/Canli-Dinle'
  },
  {
    id: 'slow-turk',
    name: '🎼 Slow Türk',
    url: 'https://radyo.duhnet.tv/ak_dtvh_slowturk',
    streamUrl: 'https://radyo.duhnet.tv/ak_dtvh_slowturk',
    category: 'pop',
    description: 'Slow Türk - Duygusal Türkçe Şarkılar',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC',
    bitrate: 128,
    votes: 1467,
    city: 'İstanbul',
    homepage: 'https://www.slowturk.com.tr/',
    favicon: 'https://www.slowturk.com.tr/_next/image?url=https%3A%2F%2Fassets.blupoint.io%2Fimg%2F85%2F330x175%2F640d8c4310c17000763c62b&w=256&q=75'
  },
  {
    id: 'numberone-turk',
    name: '1️⃣ NumberOne Türk',
    url: 'https://n10101m.mediatriple.net/numberoneturk',
    streamUrl: 'https://n10101m.mediatriple.net/numberoneturk',
    category: 'pop',
    description: 'NumberOne Türk - Türkçe Hit Müzikler',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC+',
    bitrate: 32,
    votes: 1467,
    tags: ['pop'],
    homepage: 'https://www.numberone.com.tr/2015/12/17/nr1-turk-fm-dinle-canli-radyo-dinle/'
  },
  {
    id: 'radyo-turkuvaz',
    name: '🔵 Radyo Turkuvaz',
    url: 'https://trkvz-radyolar.ercdn.net/radyoturkuvaz/playlist.m3u8',
    streamUrl: 'https://trkvz-radyolar.ercdn.net/radyoturkuvaz/playlist.m3u8',
    category: 'news',
    description: 'Radyo Turkuvaz - Haber ve Gündem',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC',
    bitrate: 64,
    votes: 781
  },
  {
    id: 'habertürk-radyo',
    name: '📺 Habertürk Radyo',
    url: 'https://haberturkradyo.radyotvonline.net/haberturkradyo',
    streamUrl: 'https://haberturkradyo.radyotvonline.net/haberturkradyo',
    category: 'news',
    description: 'Habertürk Radyo - Güncel Haber ve Analizler',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC',
    bitrate: 128,
    votes: 698,
    homepage: 'https://www.haberturkradyo.com.tr/',
    favicon: 'https://www.haberturkradyo.com.tr/wp-content/uploads/2017/07/cropped-RADYO_LOGO_Son-180x180.png'
  },
  {
    id: 'trt-radyo-haber',
    name: '📻 TRT Radyo Haber',
    url: 'https://radio-trtradyohaber.live.trt.com.tr/master.m3u8',
    streamUrl: 'https://radio-trtradyohaber.live.trt.com.tr/master.m3u8',
    category: 'news',
    description: 'TRT Radyo Haber - Güncel Haber ve Analizler',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC',
    bitrate: 140,
    votes: 930,
    tags: ['news'],
    homepage: 'https://www.trtdinle.com/channel/trt-radyo-haber',
    favicon: 'https://cdn-i.pr.trt.com.tr/trtdinle//w410/h315/q70/12530424_00-2048-1536.jpeg'
  },
  {
    id: 'borusan-klasik',
    name: '🎼 Borusan Klasik',
    url: 'http://28513.live.streamtheworld.com:3690/BORUSAN_KLASIKAAC_SC',
    streamUrl: 'http://28513.live.streamtheworld.com:3690/BORUSAN_KLASIKAAC_SC',
    category: 'classical',
    description: 'Borusan Klasik - Klasik Müzik',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC+',
    bitrate: 64,
    votes: 698,
    tags: ['classical'],
    homepage: 'https://karnaval.com/radyolar/borusanklasik'
  },
  {
    id: 'virgin-radio-api',
    name: '🎸 Virgin Radio (Live)',
    url: 'http://27743.live.streamtheworld.com/VIRGIN_RADIOAAC_SC',
    streamUrl: 'http://27743.live.streamtheworld.com/VIRGIN_RADIOAAC_SC',
    category: 'rock',
    description: 'Virgin Radio - Pop, R&B, Rap Müzik',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC+',
    bitrate: 64,
    votes: 357,
    tags: ['pop', 'r&b', 'rap'],
    homepage: 'https://www.virginradioturkiye.com/'
  },
  {
    id: 'radyo-eksen',
    name: '🎸 Radyo Eksen 99.2',
    url: 'http://eksenwmp.radyotvonline.com/;stream.mp3',
    streamUrl: 'http://eksenwmp.radyotvonline.com/;stream.mp3',
    category: 'rock',
    description: 'Radyo Eksen - Alternative Rock ve Indie',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'MP3',
    bitrate: 224,
    votes: 331,
    city: 'Istanbul',
    tags: ['alternative rock', 'indie', 'istanbul', 'rock'],
    homepage: 'http://www.radioeksen.com/'
  },
  {
    id: 'radyo-odtu',
    name: '🎓 Radyo ODTÜ',
    url: 'https://stream3.radyoodtu.com.tr:8000/',
    streamUrl: 'https://stream3.radyoodtu.com.tr:8000/',
    category: 'talk',
    description: 'Radyo ODTÜ - Üniversite Radyosu',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC+',
    bitrate: 48,
    votes: 1044,
    homepage: 'http://www.radyoodtu.com.tr/'
  },
  {
    id: 'power-turk-live',
    name: '⚡ Power Türk (Live)',
    url: 'https://live.powerapp.com.tr/powerturk/abr/powerturk/128/playlist.m3u8',
    streamUrl: 'https://live.powerapp.com.tr/powerturk/abr/powerturk/128/playlist.m3u8',
    category: 'pop',
    description: 'Power Türk - Canlı Yayın',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC',
    bitrate: 150,
    votes: 864
  },
  {
    id: 'power-dance-live',
    name: '⚡ Power Dance (Live)',
    url: 'https://listen.powerapp.com.tr/powerdance/abr/powerdance/128/playlist.m3u8',
    streamUrl: 'https://listen.powerapp.com.tr/powerdance/abr/powerdance/128/playlist.m3u8',
    category: 'dance',
    description: 'Power Dance - Dans Müziği Canlı Yayın',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC',
    bitrate: 150,
    votes: 628
  },
  // Popular Turkish Radio Stations from Radio Browser API
  {
    id: 'trt-fm',
    name: '🎵 TRT FM',
    url: 'https://radio-trtfm.live.trt.com.tr/master_720.m3u8',
    streamUrl: 'https://radio-trtfm.live.trt.com.tr/master_720.m3u8',
    category: 'pop',
    description: 'TRT FM - Türkiye Radyo Televizyon Kurumu',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC',
    bitrate: 128,
    city: 'Ankara',
    votes: 25140,
    favicon: 'https://www.trt.net.tr/Themes/trt/images/favicon.ico'
  },
  {
    id: 'trt-3',
    name: '📻 TRT 3',
    url: 'https://radio-trt3.live.trt.com.tr/master_720.m3u8',
    streamUrl: 'https://radio-trt3.live.trt.com.tr/master_720.m3u8',
    category: 'classical',
    description: 'TRT 3 - Klasik ve Sanat Müziği',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC',
    bitrate: 128,
    city: 'Ankara',
    votes: 17856,
    favicon: 'https://www.trt.net.tr/Themes/trt/images/favicon.ico'
  },
  {
    id: 'radyo-viva',
    name: '🎶 Radyo Viva',
    url: 'https://4.seslimedya.com/radyoviva/aac/4playaac.aac',
    streamUrl: 'https://4.seslimedya.com/radyoviva/aac/4playaac.aac',
    category: 'pop',
    description: 'Radyo Viva - Pop ve Türkçe Müzik',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC',
    bitrate: 64,
    city: 'İstanbul',
    votes: 14112,
    homepage: 'https://www.radyoviva.com.tr'
  },
  {
    id: 'virgin-radio-turkey',
    name: '🔥 Virgin Radio Turkey',
    url: 'https://playerservices.streamtheworld.com/api/livestream-redirect/VIRGIN_RADIO_TURKEY.mp3',
    streamUrl: 'https://playerservices.streamtheworld.com/api/livestream-redirect/VIRGIN_RADIO_TURKEY.mp3',
    category: 'pop',
    description: 'Virgin Radio Turkey - International Pop Hits',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'MP3',
    bitrate: 128,
    city: 'İstanbul',
    votes: 12936,
    homepage: 'https://www.virginradio.com.tr'
  },
  {
    id: 'radyo-d',
    name: '🎵 Radyo D',
    url: 'https://4.seslimedya.com/radyod/aac/4playaac.aac',
    streamUrl: 'https://4.seslimedya.com/radyod/aac/4playaac.aac',
    category: 'pop',
    description: 'Radyo D - Türkçe Pop Müzik',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC',
    bitrate: 64,
    city: 'İstanbul',
    votes: 10584
  },
  {
    id: 'show-radyo',
    name: '🎤 Show Radyo',
    url: 'https://moondigitalmaster.radyotvonline.net/showradyo/playlist.m3u8',
    streamUrl: 'https://moondigitalmaster.radyotvonline.net/showradyo/playlist.m3u8',
    category: 'pop',
    description: 'Show Radyo - Hit Müzikler ve Eğlence',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC',
    bitrate: 128,
    city: 'İstanbul',
    votes: 9540,
    homepage: 'https://www.showradyo.com.tr'
  },
  {
    id: 'radyo-fenomen',
    name: '⭐ Radyo Fenomen',
    url: 'https://live.radyofenomen.com/fenomen/128/icecast.audio',
    streamUrl: 'https://live.radyofenomen.com/fenomen/128/icecast.audio',
    category: 'pop',
    description: 'Radyo Fenomen - Güncel Hit Müzikler',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'MP3',
    bitrate: 128,
    city: 'İstanbul',
    votes: 8904
  },
  {
    id: 'capital-radyo',
    name: '💎 Capital Radyo',
    url: 'https://radyo.dogannet.tv/capital',
    streamUrl: 'https://radyo.dogannet.tv/capital',
    category: 'pop',
    description: 'Capital Radyo - Pop ve Rock Müzik',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'MP3',
    bitrate: 128,
    city: 'İstanbul',
    votes: 7896
  },
  {
    id: 'best-fm',
    name: '🌟 Best FM',
    url: 'https://bestfm.turkhosted.com/bestfm',
    streamUrl: 'https://bestfm.turkhosted.com/bestfm',
    category: 'pop',
    description: 'Best FM - En İyi Şarkılar',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'MP3',
    bitrate: 320,
    city: 'İstanbul',
    votes: 6912
  },
  {
    id: 'joy-fm',
    name: '😊 Joy FM',
    url: 'https://playerservices.streamtheworld.com/api/livestream-redirect/JOY_FM.mp3',
    streamUrl: 'https://playerservices.streamtheworld.com/api/livestream-redirect/JOY_FM.mp3',
    category: 'pop',
    description: 'Joy FM - Neşeli Müzikler',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'MP3',
    bitrate: 128,
    city: 'İstanbul',
    votes: 6480
  },
  {
    id: 'kral-fm',
    name: '👑 Kral FM',
    url: 'https://dygedge.radyotvonline.net/kralfm/playlist.m3u8',
    streamUrl: 'https://dygedge.radyotvonline.net/kralfm/playlist.m3u8',
    category: 'pop',
    description: 'Kral FM - Türkçe Pop Müzik',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC',
    bitrate: 128,
    city: 'İstanbul',
    votes: 5832,
    homepage: 'https://www.kralfm.com.tr'
  },
  {
    id: 'metro-fm',
    name: '🚇 Metro FM',
    url: 'https://playerservices.streamtheworld.com/api/livestream-redirect/METRO_FM.mp3',
    streamUrl: 'https://playerservices.streamtheworld.com/api/livestream-redirect/METRO_FM.mp3',
    category: 'pop',
    description: 'Metro FM - Pop ve Rock Müzik',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'MP3',
    bitrate: 128,
    city: 'İstanbul',
    votes: 5544,
    homepage: 'https://www.metrofm.com.tr'
  },
  {
    id: 'slow-turk',
    name: '🎼 Slow Türk',
    url: 'https://radyo.dogannet.tv/slowturk',
    streamUrl: 'https://radyo.dogannet.tv/slowturk',
    category: 'pop',
    description: 'Slow Türk - Duygusal Türkçe Şarkılar',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'MP3',
    bitrate: 128,
    city: 'İstanbul',
    votes: 4896
  },
  {
    id: 'trt-turku',
    name: '🪕 TRT Türkü',
    url: 'https://radio-trtturku.live.trt.com.tr/master_720.m3u8',
    streamUrl: 'https://radio-trtturku.live.trt.com.tr/master_720.m3u8',
    category: 'folk',
    description: 'TRT Türkü - Türk Halk Müziği',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC',
    bitrate: 128,
    city: 'Ankara',
    votes: 4608,
    favicon: 'https://www.trt.net.tr/Themes/trt/images/favicon.ico'
  },
  {
    id: 'number1-fm',
    name: '1️⃣ Number1 FM',
    url: 'https://n10101m.mediatriple.net/videoonlylive/mtisvwurbfcyslive/broadcast_58f5e5a2a1c23.smil/playlist.m3u8',
    streamUrl: 'https://n10101m.mediatriple.net/videoonlylive/mtisvwurbfcyslive/broadcast_58f5e5a2a1c23.smil/playlist.m3u8',
    category: 'pop',
    description: 'Number1 FM - Hit Müzikler',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC',
    bitrate: 128,
    city: 'İstanbul',
    votes: 4320
  },
  {
    id: 'alem-fm',
    name: '🌍 Alem FM',
    url: 'https://ssl5.radyotvonline.com/alemfm/alemfm.stream/playlist.m3u8',
    streamUrl: 'https://ssl5.radyotvonline.com/alemfm/alemfm.stream/playlist.m3u8',
    category: 'pop',
    description: 'Alem FM - Türkçe ve Yabancı Müzik',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC',
    bitrate: 128,
    city: 'İstanbul',
    votes: 3888,
    homepage: 'https://www.alemfm.com'
  },
  {
    id: 'radyo-mydonose',
    name: '💫 Radyo Mydonose',
    url: 'https://radyomydonose.com/ssl/128.m3u',
    streamUrl: 'https://radyomydonose.com/ssl/128.m3u',
    category: 'pop',
    description: 'Radyo Mydonose - Türkçe Pop Müzik',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'MP3',
    bitrate: 128,
    city: 'İstanbul',
    votes: 3744
  },
  {
    id: 'trt-radyo-1',
    name: '📻 TRT Radyo 1',
    url: 'https://radio-trtradyo1.live.trt.com.tr/master_720.m3u8',
    streamUrl: 'https://radio-trtradyo1.live.trt.com.tr/master_720.m3u8',
    category: 'news',
    description: 'TRT Radyo 1 - Haber ve Güncel Konular',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC',
    bitrate: 128,
    city: 'Ankara',
    votes: 3456,
    favicon: 'https://www.trt.net.tr/Themes/trt/images/favicon.ico'
  },
  {
    id: 'radyo-7',
    name: '7️⃣ Radyo 7',
    url: 'https://moondigitaledge.radyotvonline.net/radyo7/playlist.m3u8',
    streamUrl: 'https://moondigitaledge.radyotvonline.net/radyo7/playlist.m3u8',
    category: 'pop',
    description: 'Radyo 7 - Karışık Müzik',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'AAC',
    bitrate: 128,
    city: 'İstanbul',
    votes: 3312
  },
  {
    id: 'radyo-turkuvaz',
    name: '🔵 Radyo Turkuvaz',
    url: 'https://stream.turkuvazradyo.com.tr/turkuvazradyo',
    streamUrl: 'https://stream.turkuvazradyo.com.tr/turkuvazradyo',
    category: 'news',
    description: 'Radyo Turkuvaz - Haber ve Gündem',
    country: 'Turkey',
    language: 'Turkish',
    codec: 'MP3',
    bitrate: 128,
    city: 'İstanbul',
    votes: 3168
  }
];

// Guaranteed working stations for the app
export const GUARANTEED_STATIONS = RADIO_STATIONS.filter(station => station.isGuaranteed);